#pragma once
#include <string>
#include <string_view>
#include <vector>
#include <map>
#include <stdexcept>
#include <charconv>
#include <cmath>
namespace assetjson {
struct Value {char kind='n';std::string text;double number{};std::vector<Value> array;std::map<std::string,Value> object;size_t begin{},end{};const Value& get(const std::string& key)const{static Value empty;auto i=object.find(key);return i==object.end()?empty:i->second;}};
inline void utf8(std::string& s,unsigned cp){if(cp<128)s+=char(cp);else if(cp<2048){s+=char(192|(cp>>6));s+=char(128|(cp&63));}else if(cp<65536){s+=char(224|(cp>>12));s+=char(128|((cp>>6)&63));s+=char(128|(cp&63));}else{s+=char(240|(cp>>18));s+=char(128|((cp>>12)&63));s+=char(128|((cp>>6)&63));s+=char(128|(cp&63));}}
// Bounded, strict JSON for authored assets. Original slices preserve every definition field.
class Parser {std::string_view input;size_t pos{},nodes{};void fail(){throw std::runtime_error("Invalid or oversized JSON asset");}void space(){while(pos<input.size()&&(input[pos]==' '||input[pos]=='\n'||input[pos]=='\r'||input[pos]=='\t'))++pos;}char take(){if(pos>=input.size())fail();return input[pos++];}unsigned hex4(){unsigned cp=0;for(int i=0;i<4;++i){char c=take();unsigned d=c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:c>='A'&&c<='F'?c-'A'+10:99;if(d>15)fail();cp=cp*16+d;}return cp;}std::string string(){if(take()!='"')fail();std::string out;for(;;){unsigned char c=take();if(c=='"')break;if(c<32)fail();if(c!='\\'){out+=char(c);continue;}c=take();switch(c){case '"':case '\\':case '/':out+=char(c);break;case 'b':out+='\b';break;case 'f':out+='\f';break;case 'n':out+='\n';break;case 'r':out+='\r';break;case 't':out+='\t';break;case 'u':{unsigned cp=hex4();if(cp>=0xd800&&cp<=0xdbff){if(take()!='\\'||take()!='u')fail();unsigned low=hex4();if(low<0xdc00||low>0xdfff)fail();cp=0x10000+((cp-0xd800)<<10)+(low-0xdc00);}else if(cp>=0xdc00&&cp<=0xdfff)fail();utf8(out,cp);break;}default:fail();}}return out;}
 Value value(unsigned depth){space();if(depth>64||++nodes>300000||pos>=input.size())fail();Value v;v.begin=pos;char c=input[pos];if(c=='"'){v.kind='s';v.text=string();}else if(c=='{'||c=='['){++pos;v.kind=c=='{'?'o':'a';space();char end=c=='{'?'}':']';if(pos<input.size()&&input[pos]==end)++pos;else for(;;){if(c=='{'){space();auto key=string();space();if(take()!=':')fail();auto item=value(depth+1);if(!v.object.emplace(std::move(key),std::move(item)).second)fail();}else v.array.push_back(value(depth+1));space();char token=take();if(token==end)break;if(token!=',')fail();}}else if(c=='t'||c=='f'||c=='n'){auto token=c=='t'?"true":c=='f'?"false":"null";size_t count=std::char_traits<char>::length(token);if(input.substr(pos,count)!=token)fail();pos+=count;v.kind=c=='n'?'n':'b';v.number=c=='t'?1:0;}else{size_t start=pos;if(c=='-')++pos;if(pos>=input.size())fail();if(input[pos]=='0')++pos;else{if(input[pos]<'1'||input[pos]>'9')fail();while(pos<input.size()&&input[pos]>='0'&&input[pos]<='9')++pos;}if(pos<input.size()&&input[pos]=='.'){++pos;size_t digit=pos;while(pos<input.size()&&input[pos]>='0'&&input[pos]<='9')++pos;if(pos==digit)fail();}if(pos<input.size()&&(input[pos]=='e'||input[pos]=='E')){++pos;if(pos<input.size()&&(input[pos]=='+'||input[pos]=='-'))++pos;size_t digit=pos;while(pos<input.size()&&input[pos]>='0'&&input[pos]<='9')++pos;if(pos==digit)fail();}auto result=std::from_chars(input.data()+start,input.data()+pos,v.number);if(result.ec!=std::errc()||result.ptr!=input.data()+pos||!std::isfinite(v.number))fail();v.kind='d';}v.end=pos;return v;}
public:explicit Parser(std::string_view bytes):input(bytes){if(input.size()>32*1024*1024)fail();if(input.substr(0,3)=="\xef\xbb\xbf")pos=3;}Value parse(){auto out=value(0);space();if(pos!=input.size())fail();return out;}};
}
