#include "dinput8_proxy.cpp"
#include <cassert>
#include <array>
#include <iostream>
static unsigned calls,constructs,destroys;static int32_t expected_component=-1;static unsigned char component_definition[0x300];static unsigned char event_data[0x30],definition[0x420];
static void destructor(void*){}
static void allocate(uintptr_t* out,int32_t size,uintptr_t){assert(size==0x30);out[0]=1;out[1]=(uintptr_t)event_data;}
static void construct(void* out,const int32_t* id,const int32_t* component,const int32_t* color,const GeoString16* filter){assert(out==event_data&&*id==42&&*component==expected_component&&*color==0&&filter->length==0);++constructs;}
static void push(void*,const uintptr_t* ref){assert(ref[1]==(uintptr_t)event_data);++calls;}
static void destroy(uintptr_t* ref){assert(ref[1]==(uintptr_t)event_data);++destroys;}
static void lookup(uintptr_t* out,void*,const GeoString16* id){assert((id->length==7&&!memcmp((const void*)id->data,"bandage",7))||!memcmp((const void*)id->data,"vehicle_editor_add_component",28));*out=(uintptr_t)definition;}
static void lookup_component(uintptr_t* out,void*,const GeoString16* id){assert(id->length==19&&!memcmp((const void*)id->data,"gas_port_2_straight",19));*out=(uintptr_t)component_definition;}
template<class T>static void put(unsigned char* data,size_t at,T value){memcpy(data+at,&value,sizeof(value));}
static double native_x=300;
static void native_layout(void* screen,void*){double origin[]={native_x,100};memcpy((unsigned char*)screen+0x78,origin,sizeof(origin));}
int main(){
 bool registered=false;for(auto& spec:P27_HOOK_SPECS)if(!strcmp(spec.label,"native_screen_layout")){registered=true;assert(spec.body==INV_SCREEN_LAYOUT&&spec.overwrite==21&&spec.unwind_size==16&&spec.unwind[6]==0x24);}assert(registered);
 auto code=(unsigned char*)VirtualAlloc(nullptr,4096,MEM_COMMIT|MEM_RESERVE,PAGE_EXECUTE_READWRITE);assert(code);memcpy(code,INV_GIVE_EVENT,sizeof(INV_GIVE_EVENT));uintptr_t dtor=(uintptr_t)destructor,alloc=(uintptr_t)allocate,ctor=(uintptr_t)construct,drop=(uintptr_t)destroy,push_fn=(uintptr_t)push;put(code,0x108,(uintptr_t)&dtor);put(code,0x110,(uintptr_t)&alloc);put(code,0x118,(uintptr_t)&ctor);put(code,0x120,uintptr_t(0));put(code,0x128,(uintptr_t)&drop);FlushInstructionCache(GetCurrentProcess(),code,4096);
 std::array<unsigned char,0x2000> scene{},other_scene{};std::array<unsigned char,0x300> client{},klass{};std::array<unsigned char,0x900> frontend{};uintptr_t actor=0x1234;put(scene.data(),0x188,actor);put(other_scene.data(),0x188,actor);put(definition,0x408,int32_t(42));put(client.data(),0x90,(uintptr_t)klass.data());uintptr_t table[]={ (uintptr_t)&push_fn };put(klass.data(),0x80,(uintptr_t)table);put(frontend.data(),0x828,int32_t(2));g_p34_frontend=(uintptr_t)frontend.data();
 itemcatalog::Entry item;strcpy_s(item.metadata.id,"bandage");catalog_runtime::entries.push_back(item);inventory_actions::lookup=lookup;inventory_actions::give=(inventory_actions::GiveFn)code;inventory_actions::ready=true;inventory_actions::component_lookup=lookup_component;
 auto mode_code=(unsigned char*)VirtualAlloc(nullptr,4096,MEM_COMMIT|MEM_RESERVE,PAGE_EXECUTE_READWRITE);assert(mode_code);memcpy(mode_code,INV_MODE_GET,sizeof(INV_MODE_GET));uintptr_t mode_fn=(uintptr_t)mode_code;uintptr_t mode_table[]={(uintptr_t)&mode_fn};std::array<unsigned char,0x90> mode_class{};put(mode_class.data(),0x80,(uintptr_t)mode_table);put(scene.data(),0x30,(uintptr_t)mode_class.data());put(other_scene.data(),0x30,(uintptr_t)mode_class.data());put(scene.data(),0x38,int32_t(2));put(other_scene.data(),0x38,int32_t(2));session_runtime::names={"survival","creative","sandbox"};session_runtime::getter_slot=0;session_runtime::ready=true;

 assert(!inventory_actions::available()&&!inventory_actions::add("bandage"));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(inventory_actions::available());assert(!inventory_actions::add("unknown"));auto ticket=inventory_actions::add("bandage");assert(ticket&&inventory_actions::state(ticket)==ANY_ITEM_REQUEST_QUEUED);inventory_actions::tick(client.data(),scene.data(),(void*)actor);inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(calls==1&&constructs==1&&destroys==1&&inventory_actions::state(ticket)==ANY_ITEM_REQUEST_SENT);
 auto closed=inventory_actions::add("bandage");put(frontend.data(),0x828,int32_t(0));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(inventory_actions::state(closed)==ANY_ITEM_REQUEST_EXPIRED&&!inventory_actions::available()&&calls==1);put(frontend.data(),0x828,int32_t(2));inventory_actions::tick(client.data(),scene.data(),(void*)actor);auto changed=inventory_actions::add("bandage");inventory_actions::tick(client.data(),other_scene.data(),(void*)actor);assert(inventory_actions::state(changed)==ANY_ITEM_REQUEST_EXPIRED&&calls==1);
 for(int i=0;i<8;++i)assert(inventory_actions::add("bandage"));assert(!inventory_actions::add("bandage"));for(auto& r:inventory_actions::requests)if(r.state==ANY_ITEM_REQUEST_QUEUED)r.queued_at-=3000;inventory_actions::tick(client.data(),other_scene.data(),(void*)actor);assert(calls==1);
 put(scene.data(),0x188,uintptr_t(0));put(scene.data(),0x190,actor);inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(inventory_actions::add("bandage"));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(calls==2&&constructs==2&&destroys==2);
 // The mod's mode mask is enforced when queued and rechecked on dispatch.
 inventory_actions::tick(client.data(),scene.data(),(void*)actor);auto allowed=inventory_actions::add_mask("bandage",ANY_MODE_MASK_CREATIVE_SANDBOX);assert(allowed);put(scene.data(),0x38,int32_t(0));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(inventory_actions::state(allowed)==ANY_ITEM_REQUEST_EXPIRED&&calls==2&&!inventory_actions::add_mask("bandage",ANY_MODE_MASK_CREATIVE_SANDBOX));put(scene.data(),0x38,int32_t(1));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(inventory_actions::add_mask("bandage",ANY_MODE_MASK_CREATIVE_SANDBOX));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(calls==3);
 itemcatalog::Entry component;strcpy_s(component.metadata.id,"component:gas_port_2_straight");component.metadata.valid_fields=ANY_ITEM_VEHICLE_COMPONENT;catalog_runtime::entries.push_back(component);put(component_definition,0x290,int32_t(99));expected_component=99;assert(inventory_actions::add_mask(component.metadata.id,ANY_MODE_MASK_CREATIVE_SANDBOX));inventory_actions::tick(client.data(),scene.data(),(void*)actor);assert(calls==4&&constructs==4&&destroys==4);VirtualFree(mode_code,0,MEM_RELEASE);
 // Native root origin is shared by its exact reviewed render and hit-test bodies.
 std::array<unsigned char,0x100> screen{},ui{};auto id=make_const_geostring("ui_aligner");id.capacity=0;put(screen.data(),8,id);char copied[96]{};assert(p34_copy_string((uintptr_t)screen.data()+8,copied,sizeof(copied))&&!strcmp(copied,"ui_aligner"));auto malformed=id;malformed.capacity=1;put(screen.data(),8,malformed);assert(!p34_copy_string((uintptr_t)screen.data()+8,copied,sizeof(copied)));put(screen.data(),8,id);double viewport[]={1920,1080};memcpy(ui.data()+0x90,viewport,sizeof(viewport));platform::plugin_count=2;platform::current_plugin=0;screen_layout::ready=true;screen_layout::original=native_layout;
 assert(screen_layout::set("ui_aligner",2,-.1,0));assert(!screen_layout::set("ui_aligner",2,-.3,0));screen_layout::hook(screen.data(),ui.data());double x{};memcpy(&x,screen.data()+0x78,8);assert(std::abs(x-108)<.0001);
 platform::current_plugin=1;assert(screen_layout::set("ui_aligner",2,.02,0));screen_layout::hook(screen.data(),ui.data());memcpy(&x,screen.data()+0x78,8);assert(std::abs(x-146.4)<.0001);put(frontend.data(),0x828,int32_t(0));screen_layout::hook(screen.data(),ui.data());memcpy(&x,screen.data()+0x78,8);assert(x==300);put(frontend.data(),0x828,int32_t(2));platform::plugins[0].faulted=true;screen_layout::hook(screen.data(),ui.data());memcpy(&x,screen.data()+0x78,8);assert(std::abs(x-338.4)<.0001);
 platform::plugins[0].faulted=false;platform::current_plugin=1;assert(screen_layout::set("ui_aligner",2,0,0));native_x=0;screen_layout::hook(screen.data(),ui.data());memcpy(&x,screen.data()+0x78,8);assert(std::abs(x+192)<.0001);platform::current_plugin=0;assert(screen_layout::set("ui_aligner",2,0,0));screen_layout::hook(screen.data(),ui.data());memcpy(&x,screen.data()+0x78,8);assert(x==0);
 // Direct UI reads keep working without any simulation tick or player publication.
 auto ui_api=anyapi_ui_state_service();AnyUiSnapshotV1 state;
 for(int native:{1,2,13,11,55}){put(frontend.data(),0x828,int32_t(native));assert(ui_api->copy(&state)&&state.native_state==native&&state.kind==(native==1?ANY_UI_GAMEPLAY:native==2?ANY_UI_INVENTORY:ANY_UI_MENU));}
 put(frontend.data(),0x828,int32_t(-1));assert(!ui_api->copy(&state)&&state.kind==ANY_UI_UNKNOWN);state.version=2;assert(!ui_api->copy(&state));
 VirtualFree(code,0,MEM_RELEASE);std::cout<<"PASS: exact native Give-event body, one request/one event, native constructor arguments, queue limits, stale/closed/changed-world cancellation, fallback actor, screen offset ownership/state/limits\n";
}

