#define NOMINMAX
#include "map_markers.h"
#include "map_zoom.h"
#include "map_motion.h"
#include "anyapi_text_input.h"
#include <cassert>
#include <iostream>
int main(){atlas::View view;atlas::SmoothZoom motion;motion.request(view,2,{.5,.5});double previous=view.zoom;for(uint64_t tick=1000;motion.active;tick+=16){assert(motion.advance(view,tick)&&view.zoom>previous&&view.zoom<=2);assert(view.zoom-previous<.5);previous=view.zoom;}assert(view.zoom==2);auto point=view.inverse({.3,.4});motion.request(view,1.25,{.3,.4});for(uint64_t tick=2000;motion.active;tick+=16){motion.advance(view,tick);auto p=view.inverse({.3,.4});assert(std::abs(p.x-point.x)<1e-12&&std::abs(p.y-point.y)<1e-12);}motion.request(view,1.25,{.5,.5});motion.request(view,1.25,{.5,.5});assert(std::abs(motion.target-view.zoom*1.25*1.25)<1e-12);motion.cancel(view);assert(!motion.active);motion.request(view,1e6,{.5,.5});assert(motion.target==8);motion.cancel(view);motion.request(view,1e-6,{.5,.5});assert(motion.target==1);
 atlas::PoseSmoother smooth;AnySessionPlayersV1 poses;poses.world_epoch=1;poses.count=1;auto& player=poses.players[0];player.valid_fields=PLAYER_POSITION|PLAYER_FACING;player.yaw_radians=3.13;smooth.update(poses,1000);player.yaw_radians=-3.13;player.position[0]=10;smooth.update(poses,1016);assert(player.yaw_radians>3.13&&player.yaw_radians<3.16&&player.position[0]>0&&player.position[0]<10);player.position[0]=1000;smooth.update(poses,1032);assert(player.position[0]==1000);poses.world_epoch=2;player.position[0]=0;smooth.update(poses,1048);assert(player.position[0]==0);player.position[0]=10;smooth.update(poses,1500);assert(player.position[0]==10);
 AnyTextDecoder decoder;uint32_t cp{};assert(!decoder.decode(0xd83c,cp));assert(decoder.decode(0xdfe0,cp)&&cp==0x1f3e0);assert(!decoder.decode(0xdfe0,cp));assert(!decoder.decode(0xd800,cp));decoder.reset();assert(!decoder.decode(0xdc00,cp));assert(decoder.decode('A',cp)&&cp=='A');
 std::string text;assert(mapmarkers::append(text,0x1f3e0)&&text.size()==4);assert(mapmarkers::append(text,0xe9)&&text.size()==6);mapmarkers::backspace(text);assert(text.size()==4);mapmarkers::backspace(text);assert(text.empty());assert(!mapmarkers::append(text,0xd800)&&!mapmarkers::append(text,13));text=std::string(63,'x');assert(!mapmarkers::append(text,0xe9)&&text.size()==63);
 auto dir=std::filesystem::temp_directory_path()/(L"AnyMap.Markers."+std::to_wstring(GetCurrentProcessId()));mapmarkers::Store store;store.file=dir/L"markers.tsv";auto at=atlas::world({.5,.5});assert(store.save(0,at," Home ")&&store.records.size()==1&&store.records[0].name=="Home");assert(store.save(0,at,"Second")&&store.records.size()==2);assert(store.save(1,at,"Renamed"));assert(store.commit(store.records,1));mapmarkers::Store restored;restored.file=store.file;restored.load();assert(restored.records.size()==2&&restored.active==1&&restored.find(1)->name=="Renamed");assert(restored.erase(1)&&restored.records.size()==1&&!restored.active);
 assert(!restored.save(0,at,"")&&!restored.save(0,at,"\n")&&!restored.save(0,at,std::string(65,'a')));assert(!restored.save(0,{0,0},"Outside"));restored.file=dir/L"blocked"/L"markers.tsv";std::ofstream(dir/L"blocked")<<"blocked";assert(!restored.save(2,at,"Lost edit")&&restored.find(2)->name=="Second");
 std::ofstream malformed(store.file,std::ios::app);malformed<<"2\t81000\t52000\t46616b65\n"<<"3\tnan\t52000\t46616b65\n"<<"4\t81000\t52000\tc0af\n";malformed.close();mapmarkers::Store rejected;rejected.file=store.file;rejected.load();assert(rejected.records.size()==1&&rejected.rejected==3);
 std::filesystem::remove(dir/L"blocked");std::filesystem::remove(store.file);std::filesystem::remove(dir);std::cout<<"PASS: monotonic smooth zoom, accumulated requests, cursor anchor and limits; Unicode decoding/editing; durable named-marker create/rename/route/delete/reload; malformed data and failed-save retention\n";}
