"""Generates the Markdown reference (docs/reference/) from json/.

    python tools/sdk_docs.py --json json --docs docs

Pages: one per top-level namespace (types with layouts and virtual tables, functions with side, thread
tags, ABI check and how to locate them), plus globals, natives, enums, hook points, an index and
docs/reference/symbol_index.json (stable ID -> page#anchor) for tools. Hand-written guides live in
docs/guides and are not touched.
"""
import argparse
import collections
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import dump_json, load_json, write_text  # noqa: E402

TEMPLATE = ('ptr<', 'ref<', 'vector<', 'array<', 'map<', 'const ')


def ns_of(name):
    if name.startswith(TEMPLATE) or name in ('ctor', 'dtor', 'copy') or name.startswith('operator_'):
        return '_generic'
    if name.startswith('$'):
        return '_runtime'
    top = name.split('.', 1)[0]
    return top if re.fullmatch(r'[A-Za-z0-9_]+', top) else '_generic'


def anchor(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')[:90]


def esc(s):
    return (s or '').replace('|', '\\|').replace('<', '&lt;').replace('>', '&gt;')


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--json', required=True)
    ap.add_argument('--docs', required=True)
    a = ap.parse_args(argv)
    J = lambda n: load_json(os.path.join(a.json, n))
    T, F, G, N, A = J('types.json'), J('functions.json'), J('globals.json'), J('natives.json'), J('anchors.json')
    ident = J('build_identity.json')
    LOC = set(J('runtime_located.json')['functions']) if os.path.exists(os.path.join(a.json, 'runtime_located.json')) else set()
    R = os.path.join(a.docs, 'reference')
    build = 'Steam build %s, game.exe `%s`, game.gcl `%s`' % (ident['steam']['build_id'], ident['files']['game.exe']['sha256'][:16],
                                                            ident['files']['game.gcl']['sha256'][:16])
    head = ('> Generated by `tools/sdk_docs.py` from `json/` (%s). Evidence: names, layouts, signatures and vtable order '
            'are **metadata**; side/thread tags, enum numeric values and flag meanings are **static** inference; '
            '"located at runtime" marks functions found byte-identical in a running game.\n' % build)
    sym_index = {}
    by_ns_t = collections.defaultdict(list)
    for n, t in T.items():
        by_ns_t[ns_of(n)].append(t)
    by_ns_f = collections.defaultdict(list)
    for f in F:
        if f['native'] and f['name'].startswith(TEMPLATE):
            continue  # template instantiation natives are documented once in natives.md
        by_ns_f[ns_of(f['owner_type'] or f['name'])].append(f)

    def locate_txt(f):
        if f['native']:
            return 'native (see natives.md)'
        e = A['functions'].get(f['sig'], {})
        parts = []
        if 'direct' in e:
            parts.append('signature')
        if 'via_caller' in e:
            parts.append('caller slot')
        if 'chain' in e:
            parts.append('chain %d hops' % len(e['chain']['hops']))
        if 'via_typeinfo' in e:
            parts.append('typeinfo slot %d' % e['via_typeinfo']['method_slot'])
        if 'cell_chain' in e:
            parts.append('cell route')
        if f['id'] in LOC:
            parts.append('**located at runtime**')
        return ', '.join(parts) or 'not statically locatable'

    pages = sorted(set(by_ns_t) | set(by_ns_f))
    for ns in pages:
        page = 'ns/%s.md' % ns
        L = ['# `%s`' % ns, '', head]
        types = sorted(by_ns_t.get(ns, []), key=lambda t: t['name'])
        funcs = sorted(by_ns_f.get(ns, []), key=lambda f: f['sig'])
        L.append('%d types, %d functions. [Index](../index.md)' % (len(types), len(funcs)))
        L.append('')
        for t in types:
            an = anchor('t-' + t['name'])
            sym_index[t['id']] = '%s#%s' % (page, an)
            L.append('<a id="%s"></a>' % an)
            L.append('## %s `%s`' % (t['kind'], t['name']))
            L.append('')
            meta = ['size 0x%x' % t['size'], 'align %d' % t['align'], 'flags 0x%x' % t['flags'], '`%s`' % t['ref'], 'ID `%s`' % t['id']]
            if t['parent']:
                meta.append('parent `%s`' % t['parent'])
            if t['children']:
                meta.append('%d subtypes' % len(t['children']))
            L.append(' · '.join(meta))
            L.append('')
            if t['kind'] == 'enum':
                L.append(', '.join('`%s`=%d' % (v['name'], v['value']) for v in t['enum_values'][:400]))
                L.append('')
                continue
            if t['fields']:
                L += ['| Offset | Field | Type | Size |', '|---|---|---|---|']
                for fl in sorted(t['fields'], key=lambda x: x['offset']):
                    L.append('| 0x%x | %s | %s | %s |' % (fl['offset'], esc(fl['name']) if fl['name'] else '(out of scope)',
                                                          esc(fl['type']) if fl['type'] else '', fl['size'] if fl['size'] is not None else '?'))
                L.append('')
            if t['vtable']:
                own = [v for v in t['vtable'] if not v['inherited']]
                L.append('<details><summary>Method table: %d slots (%d defined or overridden here)</summary>' % (len(t['vtable']), len(own)))
                L.append('')
                L += ['| Slot | Method | Introduced by |', '|---|---|---|']
                for v in t['vtable']:
                    L.append('| %d | %s%s | %s |' % (v['slot'], esc(v['sig']), '' if v['inherited'] else ' **(own)**', esc(v['introduced_by'])))
                L += ['', '</details>', '']
            ctor = [x for x in (t['ctor'], t['copy_ctor'], t['copy'], t['dtor']) if x]
            if ctor:
                L.append('Lifetime functions: ' + ', '.join('`%s`' % esc(x) for x in ctor))
                L.append('')
        if funcs:
            L += ['## Functions', '', '| Signature | Side | Threads | ABI check | Locate | Source |', '|---|---|---|---|---|---|']
            for f in funcs:
                an = anchor('f-' + f['sig'])
                sym_index[f['id']] = '%s#%s' % (page, an)
                src = '%s:%s' % (f['source']['file'], f['source']['line']) if f['source']['file'] else ''
                L.append('| <a id="%s"></a>`%s` | %s | %s | %s | %s | %s |' % (
                    an, esc(f['sig']), f['side'], ','.join(f['threads'] or []) or '-', f.get('abi_check') or '-',
                    locate_txt(f), esc(src)))
            L.append('')
        write_text(os.path.join(R, page), '\n'.join(L) + '\n')

    # globals
    L = ['# Globals', '', head, '| Global | Type | Init order | Locate | Used by (sample) |', '|---|---|---|---|---|']
    for g in sorted(G, key=lambda g: (g['init_order'] is None, g['init_order'] or 0)):
        sym_index[g['id']] = 'globals.md#%s' % anchor('g-' + g['name'])
        loc = g['address']['locate']
        L.append('| <a id="%s"></a>`%s` | %s | %s | %s | %s |' % (
            anchor('g-' + g['name']), g['name'], esc(g['type']), g['init_order'],
            ('slot +0x%x of `%s`' % (loc['slot_offset'], esc(loc['anchor_sig']))) if loc else '-',
            ', '.join('`%s`' % esc(x) for x in g['used_by_sample'][:4])))
    write_text(os.path.join(R, 'globals.md'), '\n'.join(L) + '\n')
    # natives
    L = ['# game.exe natives', '', head,
         'RVA evidence: **metadata** = recovered from the registration code; **runtime** = read from a call cell in a '
         'running game. `json/native_bindings.json` additionally maps every gcl-declared native (including template '
         'instantiations such as `vector<s32>.size`) to the generic thunk it is bound to.', '',
         '| Native | RVA | Evidence | Byte signature unique |', '|---|---|---|---|']
    for n in N:
        sym_index[n['id']] = 'natives.md#%s' % anchor('n-' + n['sig'])
        rt = (n.get('runtime') or {}).get('rva')
        rva = n.get('thunk_rva') or rt
        ev = ('metadata+runtime' if n.get('thunk_rva') and rt == n.get('thunk_rva') else 'metadata' if n.get('thunk_rva')
              else 'runtime' if rt else 'unknown')
        L.append('| <a id="%s"></a>`%s` | %s | %s | %s |' % (anchor('n-' + n['sig']), esc(n['sig']), rva or '-', ev,
                                                         {True: 'yes', False: 'no'}.get(n.get('thunk_signature_unique'), '-')))
    write_text(os.path.join(R, 'natives.md'), '\n'.join(L) + '\n')
    # enums
    L = ['# Enums', '', head, 'Numeric values are the position in the recorded name table (static inference).', '']
    for n in sorted(x for x in T if T[x]['kind'] == 'enum'):
        L.append('- [`%s`](%s) (%d values)' % (n, sym_index[T[n]['id']].replace('ns/', 'ns/'), len(T[n]['enum_values'])))
    write_text(os.path.join(R, 'enums.md'), '\n'.join(L) + '\n')
    # hook points
    roots = ['() on_create ()', '() on_destroy ()', '() on_update ()', '() on_render ()', '() server_tick ()']
    rx = re.compile(r'\.(tick\w*|pre_tick|post_tick|post_physics|render\w*|update_ui\w*|create|destroy|post_load|'
                    r'parse_save_data|replicate\w*|on_\w+|handle_\w+|damage|interact_\w+)$')
    L = ['# Hook points', '', head,
         'Engine entry points called by game.exe, then per-object lifecycle/tick/render/UI/replication/save methods '
         'of the main managers. Hook them with a cell hook (`include/anymaker_sdk_runtime.hpp`); a virtual method\'s '
         'cell serves every caller, so hooking a base implementation runs for every subtype that does not override it.',
         '', '## Entry points', '']
    fsig = {f['sig']: f for f in F}
    for r in roots:
        if r in fsig:
            L.append('- `%s` (%s)' % (r, locate_txt(fsig[r])))
    L += ['', '## Methods', '', '| Method | Side | Threads | Locate |', '|---|---|---|---|']
    for f in F:
        if f['native'] or not rx.search(f['name']) or not f['name'].startswith(('server', 'client', 'state_manager',
                                                                                 'frontend_ui', 'renderer', 'audio_manager')):
            continue
        L.append('| [`%s`](%s) | %s | %s | %s |' % (esc(f['sig']), sym_index.get(f['id'], ''), f['side'],
                                                   ','.join(f['threads'] or []) or '-', locate_txt(f)))
    write_text(os.path.join(R, 'hook_points.md'), '\n'.join(L) + '\n')
    # index
    L = ['# Reference index', '', head, '- [Globals](globals.md) · [Natives](natives.md) · [Enums](enums.md) · '
         '[Hook points](hook_points.md) · [Systems](../systems/README.md) · [Capability matrix](../capability_matrix.md)', '',
         '| Namespace | Types | Functions |', '|---|---|---|']
    for ns in pages:
        L.append('| [`%s`](ns/%s.md) | %d | %d |' % (ns, ns, len(by_ns_t.get(ns, [])), len(by_ns_f.get(ns, []))))
    write_text(os.path.join(R, 'index.md'), '\n'.join(L) + '\n')
    dump_json(sym_index, os.path.join(R, 'symbol_index.json'), indent=None)
    print('pages', len(pages), 'symbols indexed', len(sym_index))


if __name__ == '__main__':
    main()
