"""Generates include/anymaker_sdk_types.hpp from json/types.json (+ build_identity.json).

Usage:
    python tools/sdk_header.py --json json --out include/anymaker_sdk_types.hpp


Layouts are emitted with #pragma pack(1) and explicit padding so every offset matches the
gcl metadata exactly; each struct carries static_asserts for its size and field offsets.
Bytes not covered by a recorded field are emitted as `_unknown_XXXX` arrays and must be
treated as unknown (header word, padding, or excluded content).
"""
import argparse
import json
import os
import re

_ap = argparse.ArgumentParser(description='Generate the packed C++ layout header from json/types.json')
_ap.add_argument('--json', required=True, help='json folder written by sdk_analyze.py')
_ap.add_argument('--out', required=True, help='output .hpp path')
ARGS = _ap.parse_args()
T = json.load(open(os.path.join(ARGS.json, 'types.json'), encoding='utf-8'))
IDENT = json.load(open(os.path.join(ARGS.json, 'build_identity.json'), encoding='utf-8'))
EXCLUDED_TYPE = re.compile(r'pira|banned|auth_session|auth_ticket', re.I)

PRIM = {'s32': 'int32_t', 'u32': 'uint32_t', 'f32': 'float', 'f64': 'double', 'bool': 'bool', 'u8': 'uint8_t',
        's8': 'int8_t', 'uptr': 'uintptr_t', 's64': 'int64_t', 'u64': 'uint64_t', 's16': 'int16_t', 'u16': 'uint16_t',
        'string': 'gc_string'}
PRIM_SIZE = {'s32': 4, 'u32': 4, 'f32': 4, 'f64': 8, 'bool': 1, 'u8': 1, 's8': 1, 'uptr': 8, 's64': 8, 'u64': 8,
             's16': 2, 'u16': 2, 'string': 16}
KEYWORDS = set('''alignas alignof and and_eq asm auto bitand bitor bool break case catch char char16_t char32_t class
compl const constexpr const_cast continue decltype default delete do double dynamic_cast else enum explicit export
extern false float for friend goto if inline int long mutable namespace new noexcept not not_eq nullptr operator or
or_eq private protected public register reinterpret_cast return short signed sizeof static static_assert static_cast
struct switch template this thread_local throw true try typedef typeid typename union unsigned using virtual void
volatile wchar_t while xor xor_eq NULL TRUE FALSE min max small near far IN OUT'''.split())


def strip_const(t):
    return t[6:] if t.startswith('const ') else t


_CID = {}
_CID_USED = set()


def cid(name):
    if name in _CID:
        return _CID[name]
    s = name.replace('const ', 'const_').replace(' ', '')
    s = s.replace('.', '__').replace('<', '_L_').replace('>', '_R_').replace(',', '_C_')
    s = 'gc_' + re.sub(r'[^0-9A-Za-z_]', '_', s)
    base, k = s, 2
    while s in _CID_USED:
        s = '%s_%d' % (base, k)
        k += 1
    _CID_USED.add(s)
    _CID[name] = s
    return s


def ident(n):
    n = re.sub(r'[^0-9A-Za-z_]', '_', n)
    if n[:1].isdigit():
        n = '_' + n
    return n + '_' if n in KEYWORDS else n


def inner(t, w):
    t = strip_const(t)
    return t[len(w) + 1:-1] if t.startswith(w + '<') and t.endswith('>') else None


def size_of(t):
    t = strip_const(t)
    if t in PRIM_SIZE:
        return PRIM_SIZE[t]
    if t.startswith('ptr<'):
        return 8
    if t.startswith('ref<'):
        return 16
    return T[t]['size'] if t in T else None


emitted_complete = set()
order = []
visiting = set()


def deps(name):
    t = T[name]
    out = []
    if t['parent'] and t['parent'] in T:
        out.append(t['parent'])
    for f in t['fields']:
        if f['type'] is None:
            continue
        ft = strip_const(f['type'])
        if ft in T and not ft.startswith(('ptr<', 'ref<')) and T[ft]['kind'] == 'struct':
            out.append(ft)
        elif ft in T and T[ft]['kind'] == 'enum':
            out.append(ft)
    return out


def visit(n):
    if n in emitted_complete or n in visiting:
        return
    visiting.add(n)
    for d in deps(n):
        visit(d)
    visiting.discard(n)
    emitted_complete.add(n)
    order.append(n)


for n in sorted(T):
    if T[n]['kind'] in ('struct', 'enum') and not n.startswith(('ptr<', 'ref<')):
        visit(n)


def field_ctype(ft):
    ft = strip_const(ft)
    if ft in PRIM:
        return PRIM[ft]
    p = inner(ft, 'ptr')
    if p is not None:
        p = strip_const(p)
        if p in PRIM:
            return PRIM[p] + '*'
        return (cid(p) + '*') if p in T and not EXCLUDED_TYPE.search(p) else 'void*'
    r = inner(ft, 'ref')
    if r is not None:
        r = strip_const(r)
        tgt = PRIM.get(r) or (cid(r) if r in T and not EXCLUDED_TYPE.search(r) else 'void')
        return 'gc_ref<%s>' % tgt
    if ft in T and not EXCLUDED_TYPE.search(ft):
        return cid(ft)
    return None


lines = []
w = lines.append
w('// Anymaker modding SDK - type layouts generated from game.gcl metadata.')
w('// Generated by tools/sdk_header.py. Do not edit by hand.')
w('//')
w('// Evidence: sizes, field names, field types and field offsets are METADATA (recorded in game.gcl).')
w('// `_unknown_*` byte ranges are UNKNOWN: object header, padding, or out-of-scope content.')
w('// gc_string / gc_ref internals are partly STATIC inference; see README.md "Object model".')
w('#pragma once')
w('// Build these layouts apply to (check at runtime before trusting any offset):')
w('#define ANYMAKER_SDK_SCHEMA %d' % IDENT.get('schema_version', 1))
w('#define ANYMAKER_SDK_STEAM_BUILD_ID "%s"' % ((IDENT.get('steam') or {}).get('build_id') or 'unknown'))
w('#define ANYMAKER_SDK_GAME_EXE_SHA256 "%s"' % IDENT['files'].get('game.exe', {}).get('sha256', 'unknown'))
w('#define ANYMAKER_SDK_GAME_GCL_SHA256 "%s"' % IDENT['files'].get('game.gcl', {}).get('sha256', 'unknown'))
w('#include <cstddef>')
w('#include <cstdint>')
w('')
w('#pragma pack(push, 1)')
w('')
w('// 16 bytes. +0x08 int32 length is METADATA-backed (string.length thunk game.exe+0x25d70: mov eax,[rdx+8]).')
w('// +0x00 is STATIC inference to be the character buffer pointer; +0x0C is UNKNOWN.')
w('struct gc_string { const char* data_inferred; int32_t length; uint8_t _unknown_0c[4]; };')
w('static_assert(sizeof(gc_string) == 16, "gc_string");')
w('')
w('// 16 bytes. +0x08 object pointer is STATIC inference from $ref_ctor_alloc call sites (ctor invoked on [ref+8]).')
w('// +0x00 is UNKNOWN (reference-count block).')
w('template <class T> struct gc_ref { void* _unknown_control; T* ptr; };')
w('static_assert(sizeof(gc_ref<void>) == 16, "gc_ref");')
w('')
w('// Every type whose flags bit 0 is set starts with an 8-byte header pointer (static, from dispatch code:')
w('// mov r,[obj]; mov r,[r+0x80]). The header points at runtime type info; see README.md.')
w('struct gc_typeinfo;')
w('')

# forward declarations
for n in order:
    if T[n]['kind'] == 'struct' and not EXCLUDED_TYPE.search(n):
        w('struct %s;' % cid(n))
w('')

for n in order:
    t = T[n]
    if EXCLUDED_TYPE.search(n):
        continue
    if t['kind'] == 'enum':
        w('// %s  (enum, size %d, %s). Value = position in the recorded name table (STATIC).' % (n, t['size'], t['ref']))
        ut = {4: 'int32_t', 1: 'uint8_t', 2: 'int16_t', 8: 'int64_t'}.get(t['size'], 'int32_t')
        w('enum class %s : %s {' % (cid(n), ut))
        seen_names = {}
        for v in t['enum_values']:
            nm = ident(v['name'])
            if nm in seen_names:
                seen_names[nm] += 1
                nm = '%s_dup%d' % (nm, seen_names[nm])
            else:
                seen_names[nm] = 1
            w('    %s = %d,' % (nm, v['value']))
        w('};')
        w('static_assert(sizeof(%s) == %d, "%s");' % (cid(n), t['size'], n))
        w('')
        continue
    name = cid(n)
    w('// %s  size 0x%x  %s' % (n, t['size'], t['ref']))
    if t['parent']:
        w('//   parent: %s' % t['parent'])
    w('struct %s {' % name)
    cur = 0
    asserts = []
    members = []
    if t['parent'] and t['parent'] in T and not EXCLUDED_TYPE.search(t['parent']):
        ps = T[t['parent']]['size']
        members.append((0, ps, '%s base;' % cid(t['parent']), None))
    for f in sorted(t['fields'], key=lambda f: f['offset']):
        if f['name'] is None:
            members.append((f['offset'], f['size'] or 0, None, f))
            continue
        ct = field_ctype(f['type'])
        sz = size_of(f['type'])
        excl = f['name'] is None or EXCLUDED_TYPE.search(f['type']) or EXCLUDED_TYPE.search(f['name'])
        if sz == 0 or (sz and f['offset'] + sz > t['size']):
            # empty struct (gcl may report size 1) placed at the very end: occupies no bytes
            members.append((f['offset'], 0, None, f))
            continue
        if excl or ct is None or sz is None:
            members.append((f['offset'], sz or 0, None, f))
        else:
            members.append((f['offset'], sz, '%s %s;' % (ct, ident(f['name'])), f))
    members.sort(key=lambda m: m[0])
    for off, sz, decl, f in members:
        if off < cur:
            w('    // OVERLAP at 0x%x skipped: %s' % (off, (f['name'] or 'out-of-scope') if f else 'base'))
            continue
        if off > cur:
            w('    uint8_t _unknown_%04x[0x%x];' % (cur, off - cur))
            cur = off
        if decl is None and f is not None and sz == 0:
            w('    // +0x%x %s %s  (empty type at end of struct; game.gcl gives it no bytes)' % (off, f['type'], f['name']))
            continue
        if decl is None:
            if f is not None and sz:
                why = 'out of scope' if (f['name'] is None or EXCLUDED_TYPE.search(f['type']) or EXCLUDED_TYPE.search(f['name'])) else 'type layout unknown: ' + f['type']
                w('    uint8_t _unknown_%04x[0x%x];  // %s' % (cur, sz, why))
                cur += sz
            continue
        comment = '' if f is None else '  // +0x%x %s' % (off, f['type'])
        w('    %s%s' % (decl, comment))
        if f is not None:
            asserts.append((ident(f['name']), off))
        cur = off + sz
    if cur < t['size']:
        w('    uint8_t _unknown_%04x[0x%x];' % (cur, t['size'] - cur))
    w('};')
    if t['size']:
        w('static_assert(sizeof(%s) == 0x%x, "%s size");' % (name, t['size'], n))
    else:
        w('// %s has size 0 in game.gcl; C++ gives it size 1, so it is never embedded above.' % n)
    for fn, off in asserts:
        w('static_assert(offsetof(%s, %s) == 0x%x, "%s.%s");' % (name, fn, off, n, fn))
    w('')

w('#pragma pack(pop)')
os.makedirs(os.path.dirname(os.path.abspath(ARGS.out)), exist_ok=True)
with open(ARGS.out, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('\n'.join(lines) + '\n')
print('types emitted', len(order), 'lines', len(lines))
