#pragma once
#include "anyapi_asset_json.h"
#include "anyapi_item_catalog_v1.h"
#include <fstream>
#include <filesystem>
#include <set>
#include <cstring>
#include <algorithm>
namespace itemcatalog {
struct Entry {AnyItemDefinitionV1 metadata;std::string json;};
inline std::string read(const std::filesystem::path& path){std::ifstream f(path,std::ios::binary);if(!f)throw std::runtime_error("Item asset unavailable");f.seekg(0,std::ios::end);auto size=f.tellg();if(size<0||size>32*1024*1024)throw std::runtime_error("Item asset too large");f.seekg(0);std::string out(size_t(size),'\0');if(!f.read(out.data(),out.size()))throw std::runtime_error("Incomplete item asset");return out;}
inline std::map<std::string,std::string> english(const std::filesystem::path& path){auto bytes=read(path);std::map<std::string,std::string> out;size_t at=bytes.find('\n');while(at!=std::string::npos&&++at<bytes.size()){auto end=bytes.find('\n',at);std::string_view row(bytes.data()+at,(end==std::string::npos?bytes.size():end)-at);auto a=row.find('\t'),b=row.find('\t',a+1),c=row.find('\t',b+1);if(a!=row.npos&&b!=row.npos){auto name=row.substr(b+1,c==row.npos?row.size()-b-1:c-b-1);if(!name.empty())out.emplace(std::string(row.substr(0,a)),std::string(name));}at=end;}return out;}
template<size_t N> void copy_text(char(&out)[N],const std::string& in){if(in.size()>=N||in.find('\0')!=std::string::npos)throw std::runtime_error("Item text exceeds copied API capacity");std::memcpy(out,in.c_str(),in.size()+1);}
inline std::vector<Entry> load(const std::filesystem::path& game){auto rom=game/L"rom";auto source=read(rom/L"data"/L"inventory_definitions.json");auto root=assetjson::Parser(source).parse();auto& definitions=root.get("definitions");if(definitions.kind!='a'||definitions.array.empty()||definitions.array.size()>10000)throw std::runtime_error("Item definitions schema unavailable");auto names=english(rom/L"languages_items.tsv"),descriptions=english(rom/L"languages_item_descriptions.tsv");std::set<std::string> ids;std::vector<Entry> out;
 for(auto& value:definitions.array){Entry entry;auto& item=entry.metadata;auto id=value.get("id").text;if(id.empty()||!ids.insert(id).second)throw std::runtime_error("Item definition ID missing or duplicate");copy_text(item.id,id);copy_text(item.name,names.contains(id)?names.at(id):value.get("name").text);copy_text(item.description,descriptions.contains(id)?descriptions.at(id):value.get("description").text);copy_text(item.item_class,value.get("class").text);copy_text(item.category,value.get("category").text);auto& size=value.get("inventory").get("size");if(size.kind=='a'&&size.array.size()==2&&size.array[0].kind=='d'&&size.array[1].kind=='d'&&size.array[0].number>0&&size.array[1].number>0&&size.array[0].number<=10000&&size.array[1].number<=10000&&std::floor(size.array[0].number)==size.array[0].number&&std::floor(size.array[1].number)==size.array[1].number){item.width=int(size.array[0].number);item.height=int(size.array[1].number);item.valid_fields|=ANY_ITEM_SIZE;}
 auto number=[&](const char* key,int32_t& target,uint32_t flag){auto& field=value.get(key);if(field.kind=='d'&&field.number>=0&&field.number<=INT32_MAX&&std::floor(field.number)==field.number){target=int32_t(field.number);item.valid_fields|=flag;}};number("tech_tier",item.tech_tier,ANY_ITEM_TECH_TIER);number("inv_default_stack_size",item.default_stack,ANY_ITEM_DEFAULT_STACK);entry.json=source.substr(value.begin,value.end-value.begin);out.push_back(std::move(entry));}

 auto component_source=read(rom/L"data"/L"vehicle_component_definitions.json");auto component_root=assetjson::Parser(component_source).parse();auto& components=component_root.get("definitions");if(components.kind!='a'||components.array.empty()||components.array.size()>10000)throw std::runtime_error("Component definitions schema unavailable");auto component_names=english(rom/L"languages_components.tsv"),component_descriptions=english(rom/L"languages_component_descriptions.tsv");
 for(auto& value:components.array){Entry entry;auto& item=entry.metadata;auto id=value.get("id").text;auto key="component:"+id;if(id.empty()||!ids.insert(key).second)throw std::runtime_error("Component ID missing or duplicate");copy_text(item.id,key);copy_text(item.name,component_names.contains(id)?component_names.at(id):value.get("name").text);copy_text(item.description,component_descriptions.contains(id)?component_descriptions.at(id):value.get("description").text);copy_text(item.item_class,value.get("class").text);copy_text(item.category,value.get("category").text);item.valid_fields|=ANY_ITEM_VEHICLE_COMPONENT;auto& tier=value.get("tech_tier");if(tier.kind=='d'&&tier.number>=0&&tier.number<=INT32_MAX&&std::floor(tier.number)==tier.number){item.tech_tier=int(tier.number);item.valid_fields|=ANY_ITEM_TECH_TIER;}entry.json=component_source.substr(value.begin,value.end-value.begin);out.push_back(std::move(entry));}
 return out;}
inline std::vector<std::string> mesh_paths(const Entry& entry){auto value=assetjson::Parser(entry.json).parse();std::vector<std::string> paths;auto add=[&](const std::string& path){if(!path.empty()&&std::find(paths.begin(),paths.end(),path)==paths.end())paths.push_back(path);};if(entry.metadata.valid_fields&ANY_ITEM_VEHICLE_COMPONENT){add(value.get("mesh_static").get("mesh_path").text);for(auto& mesh:value.get("meshes_dynamic").array)add(mesh.get("path").text);}else add(value.get("mesh_file").text);return paths;}
}

