#define NOMINMAX
#include <windows.h>
#include "anyapi_services_v1.h"
#include "anyapi_inventory_ui_v3.h"
#include "storage_visibility.h"
#include "anyhelpers_settings_v1.h"
#include "storage_sort.h"
#include <set>
#include <map>
namespace storage {
static const AnyInventoryUiV3* compact;
static AnyModHostV1 host;static const AnyInventoryUiV1* api;static const AnyHelpersSettingsV1* settings;
static uint64_t tokens[6]{},revision=UINT64_MAX,last_seen{},context{},next_event{};static bool enabled=true,show_matching=true,rotation=true,merge_sort=true;static int order=0,pace=120;
static std::vector<AnyStoredItemV1> items;static std::vector<AnyStorageGridV1> grids;
enum class Job {None,Transfer,SortMerge,Sort};static Job job=Job::None;
static uint32_t destination{};static bool matching{};static std::vector<uint64_t> candidates,match_types;static size_t cursor{},move_cursor{};static std::vector<storage_sort::Placement> moves;
static std::string message;static unsigned completed{},skipped{};
struct Pending {bool active{};uint64_t token{},at{};AnyStoredItemV1 before;storage_sort::Placement target;bool move{};};static Pending pending;
static void log(const std::string& value){host.log(0,"anystorage",value.c_str());}
static AnyStoredItemV1* find(uint64_t token){for(auto& a:items)if(a.token==token)return &a;return nullptr;}
static void stop(const char* why){job=Job::None;pending={};candidates.clear();moves.clear();message=why;log(std::string("JOB_END reason=")+why+" confirmed="+std::to_string(completed)+" skipped="+std::to_string(skipped));}
static void settings_read(){if(!settings||revision==settings->revision())return;revision=settings->revision();for(int i=0;i<6;++i){AnySettingValueV1 v;if(!settings->get(tokens[i],&v))continue;switch(i){case 0:enabled=v.number!=0;break;case 1:show_matching=v.number!=0;break;case 2:order=int(v.number);break;case 3:rotation=v.number!=0;break;case 4:pace=int(v.number);break;case 5:merge_sort=v.number!=0;break;}}}
static void read(const AnyInventoryUiFrameV1& f){items.clear();grids.clear();for(uint32_t side=0;side<2;++side){uint32_t n=side?f.storage_items:f.player_items,m=side?f.storage_grids:f.player_grids;for(uint32_t i=0;i<n&&i<2048;++i){AnyStoredItemV1 a;if(api->copy_item(side,i,&a))items.push_back(a);}for(uint32_t i=0;i<m&&i<128;++i){AnyStorageGridV1 g;if(api->copy_grid(side,i,&g))grids.push_back(g);}}}
static bool top_spot(const AnyStoredItemV1& a,uint32_t side,storage_sort::Placement& p){for(auto& g:grids)if(g.side==side&&!g.fixed_slots)for(int r=0;r<(rotation&&g.allow_rotation?2:1);++r){int w=storage_sort::width(a,r),h=storage_sort::height(a,r);for(int y=g.height-h;y>=0;--y)for(int x=0;x+w<=g.width;++x)if(api->can_move(a.token,g.token,x,y,r)){p={a.token,g.token,x,y,r};return true;}}return false;}
static bool visible(const AnyItemDefinitionV1* d,void*){settings_read();return enabled&&d&&storage_visibility::visible(*d);}
static void start_transfer(uint32_t to,bool only_matching){job=Job::Transfer;destination=to;matching=only_matching;candidates.clear();match_types.clear();cursor=0;completed=skipped=0;pending={};for(auto& a:items)(a.side==to?match_types:candidates).push_back(a.token);message="Transferring...";log("JOB_BEGIN transfer destination="+std::to_string(to)+" matching="+std::to_string(only_matching));}
static void plan_sort(){moves.clear();move_cursor=0;std::string error;if(!storage_sort::plan(items,grids,order==1,rotation,[](uint64_t a,uint64_t g,int r){return api->accepts(a,g,r);},moves,error)){stop(error.c_str());return;}job=Job::Sort;message="Sorting...";if(moves.empty())stop("Already sorted");}
static void start_sort(){completed=skipped=0;pending={};job=merge_sort?Job::SortMerge:Job::Sort;if(!merge_sort)plan_sort();else message="Stacking before sort...";log("JOB_BEGIN sort order="+std::to_string(order));}
static void wait_for(const AnyStoredItemV1& a,uint64_t tick,bool move=false,storage_sort::Placement target={}){pending={true,a.token,tick,a,target,move};next_event=tick+pace;}
// A native submission is not success: inspect the next replicated snapshot before continuing.
static void advance(uint64_t tick){if(job==Job::None)return;if(pending.active){auto a=find(pending.token);bool changed=pending.move?(a&&storage_sort::same(*a,pending.target)):(!a||a->side!=pending.before.side||a->quantity!=pending.before.quantity||a->grid!=pending.before.grid);
  if(changed){pending.active=false;++completed;if(job==Job::Sort)++move_cursor;log("EVENT_CONFIRMED count="+std::to_string(completed));}else if(tick-pending.at>=2500){pending.active=false;++skipped;if(job==Job::Sort||job==Job::SortMerge){stop("Game did not confirm the move");return;}++cursor;}else return;
 }if(tick<next_event)return;
 if(job==Job::Transfer){while(cursor<candidates.size()){auto a=find(candidates[cursor]);if(!a||a->side==destination){++cursor;continue;}if(matching){bool match=false;for(auto token:match_types)if(find(token)&&api->same_type(a->token,token)){match=true;break;}if(!match){++cursor;continue;}}
   for(auto& b:items)if(b.side==destination&&api->can_stack(a->token,b.token)){auto before=*a;if(api->stack(a->token,b.token)){wait_for(before,tick);return;}}
   auto before=*a;storage_sort::Placement p;if(top_spot(before,destination,p)&&api->move(p.item,p.grid,p.x,p.y,p.rotation)){wait_for(before,tick,true,p);return;}++skipped;++cursor;
  }stop(skipped?"Finished; some items could not fit":"Transfer complete");
 }else if(job==Job::SortMerge){for(auto& a:items)if(a.side==ANY_INVENTORY_STORAGE)for(auto& b:items)if(b.side==ANY_INVENTORY_STORAGE&&a.token>b.token&&api->can_stack(a.token,b.token)){auto before=a;if(api->stack(a.token,b.token)){wait_for(before,tick);return;}}plan_sort();
 }else if(job==Job::Sort){if(move_cursor>=moves.size()){stop("Sort complete");return;}auto p=moves[move_cursor];auto a=find(p.item);if(!a){stop("Inventory changed; sort stopped");return;}if(storage_sort::same(*a,p)){++move_cursor;return;}auto before=*a;if(!api->can_move(p.item,p.grid,p.x,p.y,p.rotation)||!api->move(p.item,p.grid,p.x,p.y,p.rotation)){stop("Inventory changed; sort stopped");return;}wait_for(before,tick,true,p);}
}
static void row(const char* id,const char* a,const char* at,const char* b,const char* bt,bool busy,void(*left)(),void(*right)()){if(!api->begin_row(id,2))return;if(api->button(a,at,busy))left();if(api->button(b,bt,busy))right();api->end_row();}
static void draw(const AnyInventoryUiFrameV1* frame,void*){if(!frame||frame->version!=1||frame->struct_size!=sizeof(*frame))return;settings_read();if(!enabled){if(job!=Job::None)stop("Storage tools disabled");return;}if(job!=Job::None&&context!=frame->context&&frame->tick-last_seen<=750)return;if(context!=frame->context||(last_seen&&frame->tick-last_seen>750)){if(job!=Job::None)stop("Storage changed; stopped");context=frame->context;}last_seen=frame->tick;read(*frame);std::stable_sort(items.begin(),items.end(),[](auto& a,auto& b){if(a.side!=b.side)return a.side<b.side;if(a.grid!=b.grid)return a.grid<b.grid;return a.y==b.y?a.x<b.x:a.y>b.y;});advance(frame->tick);bool busy=job!=Job::None;
 if(compact->begin_compact_row("transfer",3)){if(compact->symbol_button("withdraw","<-","Withdraw all",busy))start_transfer(ANY_INVENTORY_PLAYER,false);if(compact->symbol_button("deposit","->","Deposit all",busy))start_transfer(ANY_INVENTORY_STORAGE,false);if(compact->symbol_button("sort_action","S","Sort storage",busy))start_sort();api->end_row();}
 if(compact->begin_compact_row("matching",3)){if(show_matching){if(compact->symbol_button("stack_in","<<","Stack matching into inventory",busy))start_transfer(ANY_INVENTORY_PLAYER,true);if(compact->symbol_button("stack_out",">>","Stack matching into storage",busy))start_transfer(ANY_INVENTORY_STORAGE,true);}else{compact->symbol_button("stack_in","<<","Stack Existing buttons are disabled in Mod Settings",1);compact->symbol_button("stack_out",">>","Stack Existing buttons are disabled in Mod Settings",1);}if(compact->symbol_button("sort_order",order?"#":"A-Z",order?"Quantity: largest first":"Alphabetical: A-Z",busy))order=1-order;api->end_row();}
 if(busy||!message.empty()){if(compact->begin_compact_row("status",3)){auto info=busy?std::to_string(completed)+" moved":message;compact->symbol_button("status_text","i",info.c_str(),0);if(busy&&compact->symbol_button("cancel","X","Cancel",0))stop("Cancelled");api->end_row();}}

}
}
extern "C" __declspec(dllexport) bool AnyAPI_ModInit(const AnyModHostV1* host,AnyModCallbacksV1* callbacks){if(!host||!callbacks||host->abi!=ANYAPI_MOD_ABI||host->struct_size!=sizeof(*host)||!host->log)return false;storage::host=*host;callbacks->id="anystorage";storage::log("DLL_READY native_storage_toolbar=1");return true;}
extern "C" __declspec(dllexport) void AnyAPI_ModReady(){using namespace storage;auto services=AnyAPI_Services();if(!services)return;compact=(const AnyInventoryUiV3*)services->query("anyapi.inventory_ui",3);auto ui=compact&&compact->version==3&&compact->struct_size==sizeof(*compact)?compact->sections:nullptr;api=ui&&ui->version==2&&ui->struct_size==sizeof(*ui)?ui->operations:nullptr;if(!api||api->version!=1||api->struct_size!=sizeof(*api)||!api->register_section||!api->accepts||!api->move){api=nullptr;log("STORAGE_API unavailable=1");return;}if(!ui->register_section("storage_tools",visible,draw,nullptr,3)){log("STORAGE_SECTION registration_failed=1");return;}settings=(const AnyHelpersSettingsV1*)services->query("anyhelpers.settings",1);if(settings&&settings->version==1&&settings->struct_size==sizeof(*settings)){const char* ids[]={"enabled","show_matching","sort_order","allow_rotation","transfer_interval","stack_before_sort"},*labels[]={"Show storage tools","Show Stack Existing buttons","Default sort order","Rotate items when sorting","Transfer interval (milliseconds)","Combine stacks before sorting"},*orders[]={"Alphabetical","Quantity"};for(int i=0;i<6;++i){AnyModSettingV1 d;d.mod_id="anystorage";d.mod_name="AnyStorage";d.setting_id=ids[i];d.label=labels[i];d.order=i;d.kind=i==2?ANY_SETTING_CHOICE:i==4?ANY_SETTING_INTEGER:ANY_SETTING_BOOL;d.default_number=i==2?0:i==4?120:1;d.minimum=i==4?60:0;d.maximum=i==4?500:1;d.step=i==4?20:1;if(i==2){d.choices=orders;d.choice_count=2;}tokens[i]=settings->register_setting(&d);}log("SETTINGS_SERVICE registered=6");}else settings=nullptr;log("NATIVE_SECTION registered=1 item_browser_dependency=0");}
