#define NOMINMAX
#include <windows.h>
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <dxgi1_4.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <DirectXPackedVector.h>
#include <cassert>
#include <iostream>
#include <vector>
#include "lighting/volumetric_gpu.h"
#include "aa/scene_smaa_bindings.h"
using Microsoft::WRL::ComPtr;
int main(){std::cout<<std::unitbuf;
 ComPtr<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();ComPtr<IDXGIFactory4> factory;assert(SUCCEEDED(CreateDXGIFactory1(IID_PPV_ARGS(&factory))));ComPtr<IDXGIAdapter> adapter;assert(SUCCEEDED(factory->EnumWarpAdapter(IID_PPV_ARGS(&adapter))));ComPtr<ID3D12Device> device;assert(SUCCEEDED(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device))));ComPtr<ID3D12InfoQueue> info;device.As(&info);
 D3D12_COMMAND_QUEUE_DESC qd{};ComPtr<ID3D12CommandQueue> queue;assert(SUCCEEDED(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue))));ComPtr<ID3D12Fence> fence;assert(SUCCEEDED(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence))));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 serial{};auto wait=[&]{assert(SUCCEEDED(queue->Signal(fence.Get(),++serial)));assert(SUCCEEDED(fence->SetEventOnCompletion(serial,event)));assert(WaitForSingleObject(event,10000)==WAIT_OBJECT_0);};
 ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;assert(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator))));assert(SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))));assert(SUCCEEDED(list->Close()));
 struct Texture{ComPtr<ID3D12Resource> resource,upload,readback;D3D12_RESOURCE_DESC desc{};D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};UINT64 bytes{};};
 auto buffer=[&](ComPtr<ID3D12Resource>& out,UINT64 bytes,D3D12_HEAP_TYPE type){D3D12_HEAP_PROPERTIES hp{};hp.Type=type;D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=bytes;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;assert(SUCCEEDED(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,type==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&out))));};
 auto texture=[&](UINT w,UINT h,DXGI_FORMAT format){Texture t;t.desc.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;t.desc.Width=w;t.desc.Height=h;t.desc.DepthOrArraySize=1;t.desc.MipLevels=1;t.desc.Format=format;t.desc.SampleDesc.Count=1;t.desc.Flags=format==DXGI_FORMAT_R16G16B16A16_FLOAT?D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET:D3D12_RESOURCE_FLAG_NONE;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;assert(SUCCEEDED(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&t.desc,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&t.resource))));device->GetCopyableFootprints(&t.desc,0,1,0,&t.footprint,nullptr,nullptr,&t.bytes);buffer(t.upload,t.bytes,D3D12_HEAP_TYPE_UPLOAD);buffer(t.readback,t.bytes,D3D12_HEAP_TYPE_READBACK);return t;};
 auto copy=[&](Texture& t,bool upload){D3D12_TEXTURE_COPY_LOCATION a{},b{};a.pResource=t.resource.Get();a.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;b.pResource=upload?t.upload.Get():t.readback.Get();b.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;b.PlacedFootprint=t.footprint;if(upload)list->CopyTextureRegion(&a,0,0,0,&b,nullptr);else list->CopyTextureRegion(&b,0,0,0,&a,nullptr);};
 // Restore a deliberately different native HUD root/pipeline and clipped viewport.
 const char* shader="cbuffer Color:register(b0){float4 color;}float4 V(uint id:SV_VertexID):SV_Position{float2 uv=float2((id<<1)&2,id&2);return float4(uv*float2(2,-2)+float2(-1,1),0,1);}float4 P():SV_Target{return color;}";ComPtr<ID3DBlob> vs,ps,code,error;assert(SUCCEEDED(D3DCompile(shader,strlen(shader),nullptr,nullptr,nullptr,"V","vs_5_0",0,0,&vs,&error)));assert(SUCCEEDED(D3DCompile(shader,strlen(shader),nullptr,nullptr,nullptr,"P","ps_5_0",0,0,&ps,&error)));D3D12_ROOT_PARAMETER arg{};arg.ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;arg.Constants={0,0,4};arg.ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;D3D12_ROOT_SIGNATURE_DESC rd{1,&arg,0,nullptr,D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT};assert(SUCCEEDED(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&code,&error)));ComPtr<ID3D12RootSignature> hud_root;assert(SUCCEEDED(device->CreateRootSignature(0,code->GetBufferPointer(),code->GetBufferSize(),IID_PPV_ARGS(&hud_root))));D3D12_GRAPHICS_PIPELINE_STATE_DESC pd{};pd.pRootSignature=hud_root.Get();pd.VS={vs->GetBufferPointer(),vs->GetBufferSize()};pd.PS={ps->GetBufferPointer(),ps->GetBufferSize()};pd.BlendState.RenderTarget[0].RenderTargetWriteMask=15;pd.SampleMask=UINT_MAX;pd.RasterizerState.FillMode=D3D12_FILL_MODE_SOLID;pd.RasterizerState.CullMode=D3D12_CULL_MODE_NONE;pd.RasterizerState.DepthClipEnable=TRUE;pd.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;pd.NumRenderTargets=1;pd.RTVFormats[0]=DXGI_FORMAT_R16G16B16A16_FLOAT;pd.SampleDesc.Count=1;ComPtr<ID3D12PipelineState> hud;assert(SUCCEEDED(device->CreateGraphicsPipelineState(&pd,IID_PPV_ARGS(&hud))));D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=1;ComPtr<ID3D12DescriptorHeap> rtv;assert(SUCCEEDED(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&rtv))));hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ComPtr<ID3D12DescriptorHeap> srv;assert(SUCCEEDED(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&srv))));
 volumetric::Gpu gpu;unsigned cases{};
 auto run=[&](float shadow_value,float distance,float density,float fog,UINT steps,UINT w=64,UINT h=48,bool reversed=false,bool shadow16=false,bool farther=false,bool native_light=false){wait();assert(SUCCEEDED(allocator->Reset()));assert(SUCCEEDED(list->Reset(allocator.Get(),nullptr)));auto color=texture(w,h,DXGI_FORMAT_R16G16B16A16_FLOAT),depth=texture(w,h,DXGI_FORMAT_R32_FLOAT),shadow=texture(32,32,shadow16?DXGI_FORMAT_R16_UNORM:DXGI_FORMAT_R32_FLOAT);auto far_shadow=texture(32,32,shadow16?DXGI_FORMAT_R16_UNORM:DXGI_FORMAT_R32_FLOAT);assert(gpu.ensure(device.Get(),queue.Get(),color.desc));gpu.request_probe();
  for(auto item:{&color,&depth,&shadow,&far_shadow}){unsigned char* data{};D3D12_RANGE none{0,0};assert(SUCCEEDED(item->upload->Map(0,&none,(void**)&data)));for(UINT y=0;y<item->desc.Height;++y)for(UINT x=0;x<item->desc.Width;++x){auto p=data+item->footprint.Offset+y*item->footprint.Footprint.RowPitch;if(item==&color){auto half=(DirectX::PackedVector::HALF*)p+x*4;for(UINT c=0;c<3;++c)half[c]=DirectX::PackedVector::XMConvertFloatToHalf(.05f);half[3]=DirectX::PackedVector::XMConvertFloatToHalf(1);}else if((item==&shadow||item==&far_shadow)&&shadow16)((uint16_t*)p)[x]=uint16_t(std::clamp(item==&shadow&&farther?(reversed?0.f:1.f):shadow_value,0.f,1.f)*65535.f);else ((float*)p)[x]=(item==&shadow||item==&far_shadow)?(item==&shadow&&farther?(reversed?0.f:1.f):shadow_value):reversed?.1f/distance:1-.1f/distance;}item->upload->Unmap(0,nullptr);copy(*item,true);auto b=volumetric::barrier(item->resource.Get(),D3D12_RESOURCE_STATE_COPY_DEST,item==&color?D3D12_RESOURCE_STATE_RENDER_TARGET:D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);list->ResourceBarrier(1,&b);}
  volumetric::Frame f;f.sun={0,0,1,reversed?2.f:1.f};if(reversed)f.projection={0,.1f,1,0};f.medium={density,0,0,.4f};f.controls={float(steps),100,4,fog};f.shadow[0]=f.shadow[5]=.01f;f.shadow[10]=reversed?-.001f:.001f;f.shadow[14]=reversed?1.f:0.f;f.shadow[15]=1;if(native_light){f.sun={.462083f,0,.886829f,reversed?2.f:1.f};f.sun_color={.305571f,.280569f,.245261f,0};f.medium[3]=.35f;f.controls[2]=3;}if(farther){f.additional_shadows[0]=f.shadow;f.shadow[12]=10;f.forward[3]=2;}
  scene_smaa::Bindings saved;saved.signature(hud_root.Get());saved.pipeline=hud.Get();saved.heap_count=1;saved.heaps[0]=srv.Get();saved.topology=D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST;saved.viewport_count=saved.scissor_count=saved.target_count=1;saved.viewports[0]={0,0,8,8,0,1};saved.scissors[0]={0,0,4,8};device->CreateRenderTargetView(color.resource.Get(),nullptr,rtv->GetCPUDescriptorHandleForHeapStart());saved.targets[0]=rtv->GetCPUDescriptorHandleForHeapStart();float green[]={0,1,0,1};saved.constants(0,4,green,0);assert(saved.ready());std::array<ID3D12Resource*,8> shadows{};shadows.fill(shadow.resource.Get());if(farther)shadows[1]=far_shadow.resource.Get();std::array<D3D12_RESOURCE_STATES,8> states{};states.fill(D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);assert(gpu.record(list.Get(),color.resource.Get(),depth.resource.Get(),D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,shadows,states,f));saved.restore(list.Get());list->DrawInstanced(3,1,0,0);
  auto b=volumetric::barrier(color.resource.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE);list->ResourceBarrier(1,&b);copy(color,false);assert(SUCCEEDED(list->Close()));ID3D12CommandList* lists[]={list.Get()};volumetric::Gpu::ProbeStats premature;assert(!gpu.probe(premature));queue->ExecuteCommandLists(1,lists);gpu.submitted(queue.Get(),1,lists);wait();volumetric::Gpu::ProbeStats probe;bool probe_ready=gpu.probe(probe);std::cout<<"Probe ready="<<probe_ready<<" coverage="<<probe.coverage<<" lit="<<probe.lit_average<<" distance="<<probe.distance<<std::endl;assert(probe_ready&&probe.coverage>.95f);bool illuminated=reversed?shadow_value<.5f:shadow_value>.5f;assert(illuminated?probe.lit_average>.95f:probe.lit_average<.05f);assert(!gpu.probe(probe));unsigned char* pixels{};D3D12_RANGE range{0,SIZE_T(color.bytes)};assert(SUCCEEDED(color.readback->Map(0,&range,(void**)&pixels)));auto at=[&](UINT x,UINT y,UINT c){auto p=(const DirectX::PackedVector::HALF*)(pixels+color.footprint.Offset+y*color.footprint.Footprint.RowPitch);return DirectX::PackedVector::XMConvertHalfToFloat(p[x*4+c]);};assert(at(2,2,0)==0&&at(2,2,1)==1&&at(2,2,2)==0);assert(at(5,2,1)!=1);float result=at(w/2,h/2,0);assert(std::isfinite(result)&&result>=0);assert(at(w/2,h/2,3)==1);color.readback->Unmap(0,nullptr);++cases;return result;};
 for(UINT steps:{16u,24u,32u,48u}){float lit=run(1,100,.02f,0,steps),blocked=run(0,100,.02f,0,steps);assert(lit>blocked+.05f);std::cout<<"Occluded shafts steps="<<steps<<" lit="<<lit<<" blocked="<<blocked<<'\n';}
 for(UINT steps:{16u,24u,32u,48u}){float lit=run(0,100,.02f,0,steps,64,48,true),blocked=run(1,100,.02f,0,steps,64,48,true);assert(lit>blocked+.05f);std::cout<<"Reversed-depth shafts steps="<<steps<<" lit="<<lit<<" blocked="<<blocked<<'\n';}
 for(UINT steps:{16u,24u,32u,48u}){float lit=run(0,100,.02f,0,steps,64,48,true,true),blocked=run(1,100,.02f,0,steps,64,48,true,true);assert(lit>blocked+.05f);std::cout<<"Native R16 shadow shafts steps="<<steps<<" lit="<<lit<<" blocked="<<blocked<<'\n';}
 // The near cascade deliberately does not cover the view. The second must
 // supply occlusion instead of treating all farther samples as fully lit.
 for(UINT steps:{16u,24u,32u,48u}){float lit=run(0,100,.02f,0,steps,64,48,true,true,true),blocked=run(1,100,.02f,0,steps,64,48,true,true,true);assert(lit>blocked+.05f);std::cout<<"Farther cascade shafts steps="<<steps<<" lit="<<lit<<" blocked="<<blocked<<'\n';}
 // Regression at measured game sun RGB, low fog, and the captured sun angle:
 // raw phase normalization used to leave this contrast almost invisible.
 for(UINT steps:{16u,24u,32u,48u}){float lit=run(0,30,.001f,1,steps,64,48,true,true,true,true),blocked=run(1,30,.001f,1,steps,64,48,true,true,true,true);assert(lit>blocked+.04f);std::cout<<"Measured-light shafts steps="<<steps<<" lit="<<lit<<" blocked="<<blocked<<'\n';}
 float nearby=run(1,2,.02f,1,24),distant=run(1,100,.02f,1,24);assert(distant>nearby+.15f);assert(std::abs(run(1,100,0,1,24)-.05f)<.001f);assert(std::abs(run(1,100,0,1,24,96,64)-.05f)<.001f);
 if(info){for(UINT64 i=0;i<info->GetNumStoredMessagesAllowedByRetrievalFilter();++i){SIZE_T n{};info->GetMessage(i,nullptr,&n);std::vector<unsigned char> data(n);auto m=(D3D12_MESSAGE*)data.data();info->GetMessage(i,m,&n);if(m->Severity==D3D12_MESSAGE_SEVERITY_ERROR||m->Severity==D3D12_MESSAGE_SEVERITY_CORRUPTION){std::cerr<<m->pDescription<<'\n';assert(false);}}}CloseHandle(event);std::cout<<"PASS: "<<cases<<" HDR lighting GPU cases: shadow occlusion, depth-limited fog, zero-density identity, resizing, alpha and crisp restored HUD\n";
}
