#define NOMINMAX
#include <windows.h>
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <dxgi1_4.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <cassert>
#include <iostream>
#include <vector>
#include "aa/scene_smaa_gpu.h"
#include "aa/scene_smaa_bindings.h"
using Microsoft::WRL::ComPtr;
int main(){std::cout<<std::unitbuf;
 ComPtr<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();
 ComPtr<IDXGIFactory4> factory;assert(SUCCEEDED(CreateDXGIFactory1(IID_PPV_ARGS(&factory))));ComPtr<IDXGIAdapter> warp;assert(SUCCEEDED(factory->EnumWarpAdapter(IID_PPV_ARGS(&warp))));ComPtr<ID3D12Device> device;assert(SUCCEEDED(D3D12CreateDevice(warp.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device))));ComPtr<ID3D12InfoQueue> info;device.As(&info);
 D3D12_COMMAND_QUEUE_DESC qd{};ComPtr<ID3D12CommandQueue> queue;assert(SUCCEEDED(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue))));ComPtr<ID3D12Fence> fence;assert(SUCCEEDED(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence))));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 serial{};
 auto wait=[&]{assert(SUCCEEDED(queue->Signal(fence.Get(),++serial)));assert(SUCCEEDED(fence->SetEventOnCompletion(serial,event)));assert(WaitForSingleObject(event,10000)==WAIT_OBJECT_0);};
 ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;assert(SUCCEEDED(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator))));assert(SUCCEEDED(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list))));assert(SUCCEEDED(list->Close()));
 // Deliberately different HUD pipeline/root/viewport/scissor, restored after AA.
 D3D12_ROOT_PARAMETER arg{};arg.ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;arg.Constants={0,0,4};arg.ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;D3D12_ROOT_SIGNATURE_DESC rd{1,&arg,0,nullptr,D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT};ComPtr<ID3DBlob> signature,errors,vs,ps;assert(SUCCEEDED(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&signature,&errors)));ComPtr<ID3D12RootSignature> root;assert(SUCCEEDED(device->CreateRootSignature(0,signature->GetBufferPointer(),signature->GetBufferSize(),IID_PPV_ARGS(&root))));
 const char* shader="cbuffer Color:register(b0){float4 color;}float4 V(uint id:SV_VertexID):SV_Position{float2 uv=float2((id<<1)&2,id&2);return float4(uv*float2(2,-2)+float2(-1,1),0,1);}float4 P():SV_Target{return color;}";assert(SUCCEEDED(D3DCompile(shader,strlen(shader),nullptr,nullptr,nullptr,"V","vs_5_0",0,0,&vs,&errors)));assert(SUCCEEDED(D3DCompile(shader,strlen(shader),nullptr,nullptr,nullptr,"P","ps_5_0",0,0,&ps,&errors)));
 D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=1;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ComPtr<ID3D12DescriptorHeap> srv;assert(SUCCEEDED(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&srv))));hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_NONE;ComPtr<ID3D12DescriptorHeap> rtv;assert(SUCCEEDED(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&rtv))));
 scene_smaa::Gpu aa;
 auto check=[&](UINT w,UINT h,DXGI_FORMAT format,UINT quality,bool flat,bool enhanced=false,bool straight=false,float sharpen=0){
  wait();assert(SUCCEEDED(allocator->Reset()));assert(SUCCEEDED(list->Reset(allocator.Get(),nullptr)));
  D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC td{};td.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;td.Width=w;td.Height=h;td.DepthOrArraySize=1;td.MipLevels=1;td.Format=format;td.SampleDesc.Count=1;td.Flags=D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;ComPtr<ID3D12Resource> back;assert(SUCCEEDED(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&back))));assert(aa.ensure(device.Get(),queue.Get(),td));
  UINT64 bytes{};D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};device->GetCopyableFootprints(&td,0,1,0,&footprint,nullptr,nullptr,&bytes);D3D12_RESOURCE_DESC buffer{};buffer.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;buffer.Width=bytes;buffer.Height=1;buffer.DepthOrArraySize=1;buffer.MipLevels=1;buffer.SampleDesc.Count=1;buffer.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ComPtr<ID3D12Resource> upload,readback;hp.Type=D3D12_HEAP_TYPE_UPLOAD;assert(SUCCEEDED(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&buffer,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&upload))));hp.Type=D3D12_HEAP_TYPE_READBACK;assert(SUCCEEDED(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&buffer,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&readback))));unsigned char* memory{};D3D12_RANGE empty{0,0};assert(SUCCEEDED(upload->Map(0,&empty,(void**)&memory)));for(UINT y=0;y<h;++y)for(UINT x=0;x<w;++x){auto p=memory+footprint.Offset+y*footprint.Footprint.RowPitch+x*4;unsigned char c=flat?117:((straight?x>w/2:float(x)>.6f*y+15)?255:0);p[0]=p[1]=p[2]=c;p[3]=255;}upload->Unmap(0,nullptr);D3D12_TEXTURE_COPY_LOCATION to{};to.pResource=back.Get();to.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;D3D12_TEXTURE_COPY_LOCATION from{};from.pResource=upload.Get();from.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;from.PlacedFootprint=footprint;list->CopyTextureRegion(&to,0,0,0,&from,nullptr);auto barrier=scene_smaa::transition(back.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_RENDER_TARGET);list->ResourceBarrier(1,&barrier);
  D3D12_GRAPHICS_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.VS={vs->GetBufferPointer(),vs->GetBufferSize()};pd.PS={ps->GetBufferPointer(),ps->GetBufferSize()};pd.BlendState.RenderTarget[0].RenderTargetWriteMask=15;pd.RasterizerState.FillMode=D3D12_FILL_MODE_SOLID;pd.RasterizerState.CullMode=D3D12_CULL_MODE_NONE;pd.RasterizerState.DepthClipEnable=TRUE;pd.SampleMask=UINT_MAX;pd.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;pd.NumRenderTargets=1;pd.RTVFormats[0]=format;pd.SampleDesc.Count=1;ComPtr<ID3D12PipelineState> hud;assert(SUCCEEDED(device->CreateGraphicsPipelineState(&pd,IID_PPV_ARGS(&hud))));
  scene_smaa::Bindings saved;saved.signature(root.Get());saved.pipeline=hud.Get();saved.heap_count=1;saved.heaps[0]=srv.Get();saved.topology=D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST;saved.viewport_count=saved.scissor_count=saved.target_count=1;saved.viewports[0]={0,0,8,8,0,1};saved.scissors[0]={0,0,4,8};device->CreateRenderTargetView(back.Get(),nullptr,rtv->GetCPUDescriptorHandleForHeapStart());saved.targets[0]=rtv->GetCPUDescriptorHandleForHeapStart();float green[]={0,1,0,1};saved.constants(0,4,green,0);assert(saved.ready());
  scene_smaa::Extra extra;extra.sharpen=sharpen;aa.record(list.Get(),back.Get(),quality,enhanced,sharpen>0?&extra:nullptr);saved.restore(list.Get());list->DrawInstanced(3,1,0,0);
  barrier=scene_smaa::transition(back.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE);list->ResourceBarrier(1,&barrier);from.pResource=back.Get();from.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;to.pResource=readback.Get();to.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;to.PlacedFootprint=footprint;list->CopyTextureRegion(&to,0,0,0,&from,nullptr);assert(SUCCEEDED(list->Close()));ID3D12CommandList* lists[]={list.Get()};queue->ExecuteCommandLists(1,lists);wait();D3D12_RANGE range{0,SIZE_T(bytes)};assert(SUCCEEDED(readback->Map(0,&range,(void**)&memory)));unsigned smooth{},softness{};for(UINT y=10;y<h-2;++y)for(UINT x=10;x<w-2;++x){auto p=memory+footprint.Offset+y*footprint.Footprint.RowPitch+x*4;if(straight)assert(p[0]==(x>w/2?255:0)&&p[0]==p[1]&&p[1]==p[2]);else if(flat)assert(abs(int(p[0])-117)<=1&&p[0]==p[1]&&p[1]==p[2]);else {softness+=std::min(unsigned(p[0]),255u-p[0]);if(p[0]>3&&p[0]<252)++smooth;}}auto ui=memory+footprint.Offset+2*footprint.Footprint.RowPitch+2*4;assert(ui[0]==0&&ui[1]==255&&ui[2]==0);auto clipped=memory+footprint.Offset+2*footprint.Footprint.RowPitch+6*4;assert(clipped[1]!=255||clipped[0]==255);if(!flat&&!straight)assert(smooth>20);readback->Unmap(0,&empty);std::cout<<"PASS: SMAA quality="<<quality<<" size="<<w<<'x'<<h<<" blended_edge_pixels="<<smooth<<" edge_blending="<<softness<<" enhanced="<<enhanced<<" flat="<<flat<<" restored HUD stays crisp and clipped\n";return softness;
 };
 for(UINT quality=0;quality<4;++quality){check(64,64,DXGI_FORMAT_R8G8B8A8_UNORM,quality,false);check(64,64,DXGI_FORMAT_R8G8B8A8_UNORM,quality,true);}check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,false);check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,true);
 auto ordinary=check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,false);auto enhanced=check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,false,true);assert(enhanced>ordinary);check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,true,true);
 check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,false,false,true);check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,false,true,true);
 // Sharpening goes through the offscreen resolve and output pass: flat stays flat, straight edges stay exact, the HUD is restored.
 check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,true,false,false,.8f);check(96,80,DXGI_FORMAT_B8G8R8A8_UNORM,3,false,false,true,.8f);check(64,64,DXGI_FORMAT_R8G8B8A8_UNORM,2,false,false,false,.3f);
 if(info){for(UINT64 i=0;i<info->GetNumStoredMessages();++i){SIZE_T length{};info->GetMessage(i,nullptr,&length);std::vector<unsigned char> storage(length);auto message=(D3D12_MESSAGE*)storage.data();assert(SUCCEEDED(info->GetMessage(i,message,&length)));if(message->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){std::cerr<<message->pDescription<<'\n';assert(false);}}}wait();CloseHandle(event);std::cout<<"PASS: 18 GPU cases including stronger enhanced edge blending and preserved straight edges, lookup upload, repeat frames, resize, RGBA/BGRA, state restoration and no D3D12 errors\n";
}
