#include "dinput8_proxy.cpp"
#include <cassert>
#include <iostream>
#include "storage_visibility.h"
static int event_calls,table_calls,end_calls,button_calls;
static inventory_ui::NativeId submitted,target;
static void fake_in(void*,const inventory_ui::NativeId* a){submitted=*a;++event_calls;}
static void fake_out(void*,const inventory_ui::NativeId* a,const inventory_ui::NativeVector* v){submitted=*a;assert(v->count==1&&v->stride==24);target=*(inventory_ui::NativeId*)v->data;++event_calls;}
static void table(void*,const GeoString16* id,const int32_t* columns,const Vec2S32* size,const int32_t*){assert(id->length>20&&(*columns==2||*columns==3)&&size->y==1);++table_calls;}
static void end(void*){++end_calls;}
static void fake_button(uint8_t* out,void*,const GeoString16*,const GeoString16*,const Vec2S32*,const uintptr_t*,const bool* disabled,const bool*){++button_calls;*out=*disabled?0:1;}
static void enter(uint8_t* out,void*){*out=1;}
static int callback_calls;
static void callback(const AnyInventoryUiFrameV1*,void*){++callback_calls;}
static void title(uint8_t* out,void*,const GeoString16*,const GeoString16*,const uintptr_t*,const Vec2S32*){*out=0;}
static bool filter(const AnyItemDefinitionV1* d,void*){return storage_visibility::visible(*d);}
static int expected_height;
static void column(void*,void*,void*,void*,const int32_t*,const bool*,const inventory_ui::NativeVector* list,const int32_t*,void*,const int32_t*,void*,void*,void*,int32_t*,void*){assert(list->count==1&&((inventory_ui::Descriptor*)list->data)->flags==expected_height);}
static inventory_ui::NativeStored fixture_item;static inventory_ui::NativeGrid fixture_grid;static int32_t fixture_id=11;
static void get_id(uintptr_t* out,void*){*out=(uintptr_t)&fixture_id;}
static void ctor_items(inventory_ui::NativeVector* v){*v={};v->stride=32;}
static void ctor_grids(inventory_ui::NativeVector* v){*v={};v->stride=48;}
static void dtor(inventory_ui::NativeVector*){}
static void get_items(void*,const inventory_ui::Descriptor*,inventory_ui::NativeVector* v){v->data=(uintptr_t)&fixture_item;v->count=v->capacity=1;}
static void get_grids(void*,const inventory_ui::Descriptor*,inventory_ui::NativeVector* v){v->data=(uintptr_t)&fixture_grid;v->count=v->capacity=1;}
template<class T>static void put(unsigned char* p,size_t at,T value){memcpy(p+at,&value,sizeof(value));}
static void tag(uint8_t* out,void*,const GeoString16*,const GeoString16* label,const Vec2S32* size,const uint32_t*,const bool*){assert(size->x==2&&size->y==1&&label->length<=4);*out=1;}
static int screen_calls,tip_calls;static std::string tooltip_copy;
static void screen(void*,const GeoString16*,const Vec2S32*,const int32_t*,const int32_t* vertical,const int32_t*,const int32_t* content_vertical,const int32_t*,const bool* capture){assert(*vertical==2&&*content_vertical==2&&!*capture);++screen_calls;}
static void screen_end(void*){++screen_calls;}
static bool cursor(Vec2S32* p,Vec2S32* viewport){*p={38,19};*viewport={40,20};return true;}
static void position(void*,const GeoString16*,const Vec2S32* point,const Vec2S32* size){assert(point->x+size->x<=40&&point->y+size->y<=20);}
static void background(void*,const GeoString16*,const bool*,const uint32_t* color){assert(*color==0xb0202020);}
static void tooltip(void*,const GeoString16*,const GeoString16* text,const Vec2S32*,const int32_t*,const uint32_t*){char value[256]{};assert(p34_copy_string((uintptr_t)text,value,sizeof(value)));tooltip_copy=value;++tip_calls;}
int main(){using namespace inventory_ui;unsigned char frontend[0x900]{};put(frontend,0x828,int32_t(2));g_p34_frontend=(uintptr_t)frontend;platform::plugin_count=2;platform::current_plugin=0;ready=true;inventory_ui::quick_in=fake_in;inventory_ui::quick_out=fake_out;menus::native_table=table;menus::native_end=end;menus::native_button=fake_button;menus::native_enter=enter;
 assert(add("storage_tools",callback,nullptr));assert(!add("storage_tools",callback,nullptr));platform::current_plugin=1;assert(add("storage_tools",callback,nullptr));
 Context c;c.storage.type=2;c.storage.floor=19;c.storage.parent=42;c.storage.peer=0;c.storage.part=-1;c.client=frontend;c.ui=frontend;c.frame.context=123;Item a;a.copy.token=1;a.copy.side=0;a.copy.quantity=5;a.copy.capacity=10;a.definition=123;a.variant=7;a.id=parent_id(c.storage,55);c.items.push_back(a);a.copy.token=2;a.copy.side=1;a.variant=8;c.items.push_back(a);Grid g;g.copy.token=100;g.copy.side=1;g.copy.width=8;g.copy.height=12;c.grids.push_back(g);active=&c;drawing=&sections[0];
 assert(same_type(1,1)&&!same_type(1,2));c.items[1].variant=7;assert(same_type(1,2));AnyStoredItemV1 copy;assert(copy_item(0,0,&copy)&&copy.token==1);assert(!copy_item(0,1,&copy));copy.version=9;assert(!copy_item(0,0,&copy));AnyStorageGridV1 grid;assert(copy_grid(1,0,&grid)&&grid.width==8);assert(begin_row("transfer",2));assert(button("withdraw","Withdraw All",0));assert(!button("off","Disabled",1));end_row();assert(table_calls==1&&end_calls==1&&button_calls==2);
 platform::frames=1;assert(quick_store(1,1)&&event_calls==1&&submitted.item==55&&target.item==42&&target.component==-1&&target.floor==19);assert(!quick_store(1,1)&&event_calls==1);platform::frames=2;assert(quick_store(2,0)&&event_calls==2);put(frontend,0x828,int32_t(13));platform::frames=3;assert(!quick_store(1,1)&&!begin_row("transfer",2)&&!copy_grid(1,0,&grid)&&event_calls==2);put(frontend,0x828,int32_t(2));platform::plugins[0].faulted=true;assert(!quick_store(1,1));active=nullptr;drawing=nullptr;
 // Exercise copied collections using the actual reviewed scalar getter bodies.
 auto code=(unsigned char*)VirtualAlloc(nullptr,4096,MEM_RESERVE|MEM_COMMIT,PAGE_EXECUTE_READWRITE);assert(code);memcpy(code,ST_QUANTITY_6817,sizeof(ST_QUANTITY_6817));memcpy(code+128,ST_CAPACITY_6816,sizeof(ST_CAPACITY_6816));uintptr_t qty=(uintptr_t)code,cap=(uintptr_t)(code+128),idfn=(uintptr_t)get_id,mergefn=0;unsigned char object[0x100]{},klass[0x100]{},propklass[0x100]{},definition[0x200]{};uintptr_t table[]={ (uintptr_t)&qty,(uintptr_t)&cap,(uintptr_t)&mergefn },ptable[]={ (uintptr_t)&idfn };put(klass,0x80,(uintptr_t)table);put(propklass,0x80,(uintptr_t)ptable);put(object,0,(uintptr_t)klass);put(object,8,(uintptr_t)propklass);put(object,0x28,(uintptr_t)definition);put(definition,0x10,make_const_geostring("Bandage"));put(definition,0x170,int32_t(2));put(definition,0x174,int32_t(1));id_slot=0;quantity_slot=0;capacity_slot=8;merge_slot=16;
 itemcatalog::Entry entry;strcpy_s(entry.metadata.id,"bandage");strcpy_s(entry.metadata.name,"Bandage");catalog_runtime::entries.push_back(entry);fixture_item.item=(uintptr_t)object;fixture_item.grid=0;fixture_item.x=2;fixture_item.y=3;fixture_grid.width=7;fixture_grid.height=9;fixture_grid.origin_x=3;fixture_grid.origin_y=4;fixture_grid.rotate=1;items_ctor=ctor_items;grids_ctor=ctor_grids;items_dtor=grids_dtor=dtor;inventory_ui::get_items=::get_items;inventory_ui::get_grids=::get_grids;Context copied;copied.inventory=frontend;assert(collect(copied,c.storage,1));assert(copied.items.size()==1&&copied.grids.size()==1&&copied.items[0].id.item==11&&copied.items[0].copy.width==2&&!strcmp(copied.items[0].copy.definition,"bandage")&&copied.grids[0].copy.width==7&&copied.grids[0].copy.height==9);
 memcpy(code+256,ST_MERGE_8461,sizeof(ST_MERGE_8461));mergefn=(uintptr_t)(code+256);unsigned char part[0x300]{};put(part,0,make_const_geostring("gas_port"));put(part,0x10,make_const_geostring("Gas Port Native"));put(object,0x58,(uintptr_t)part);entry={};strcpy_s(entry.metadata.id,"component:gas_port");strcpy_s(entry.metadata.name,"Gas Port");catalog_runtime::entries.push_back(entry);Context components;components.inventory=frontend;assert(collect(components,c.storage,1)&&components.items[0].variant==(uintptr_t)part&&!strcmp(components.items[0].copy.definition,"component:gas_port")&&!strcmp(components.items[0].copy.name,"Gas Port"));VirtualFree(code,0,MEM_RELEASE);
 // Byte-level native vector fixture: flags +8, item count +12, capacity +16.
 // Previously tests constructed the mistaken struct itself and missed this gate.
 unsigned char raw[40]{};put(raw,0,(uintptr_t)&c.storage);put(raw,8,int32_t(0));put(raw,12,int32_t(1));put(raw,16,int32_t(32));put(raw,20,int32_t(88));NativeVector view;assert(vector_view((uintptr_t)raw,view,88)&&view.count==1&&view.capacity==32&&view.unknown==0);
 // Exercise the real native title hook, including external-storage identification.
 // Recreate ordinary (non-component) item data before the callback snapshot.
 auto scalar=(unsigned char*)VirtualAlloc(nullptr,4096,MEM_RESERVE|MEM_COMMIT,PAGE_EXECUTE_READWRITE);assert(scalar);memcpy(scalar,ST_QUANTITY_6817,sizeof(ST_QUANTITY_6817));memcpy(scalar+128,ST_CAPACITY_6816,sizeof(ST_CAPACITY_6816));qty=(uintptr_t)scalar;cap=(uintptr_t)(scalar+128);mergefn=0;
 unsigned char native_data[0x98]{};NativeVector empty{};empty.stride=88;memcpy(native_data+0x20,&empty,40);memcpy(native_data+0x48,&empty,40);memcpy(native_data+0x70,raw,40);c.data=native_data;c.inventory=frontend;c.scene=frontend;c.items.clear();c.grids.clear();c.frame={};active=&c;original_title=title;platform::plugins[0].faulted=false;uint8_t selected=0;GeoString16 label=make_const_geostring("Crate");uintptr_t icon=0;Vec2S32 title_size{8,2};title_hook(&selected,frontend,&label,&label,&icon,&title_size);assert(callback_calls==2&&c.frame.storage_items==1&&c.frame.storage_grids==1);put(native_data,0x70+12,int32_t(0));title_hook(&selected,frontend,&label,&label,&icon,&title_size);assert(callback_calls==2);active=nullptr;VirtualFree(scalar,0,MEM_RELEASE);
 sections.clear();platform::current_plugin=0;assert(add_v2("storage_tools",filter,callback,nullptr,4));Descriptor chest=c.storage;chest.item=0;chest.name=make_const_geostring("Crate");chest.flags=8;NativeVector native_list;native_list.data=(uintptr_t)&chest;native_list.count=1;native_list.capacity=32;native_list.stride=88;memcpy(native_data+0x70,&native_list,40);original_column=column;expected_height=12;column_hook(frontend,frontend,frontend,native_data,nullptr,nullptr,&native_list,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr);assert(chest.flags==8);
 chest.name=make_const_geostring("Torch");expected_height=8;column_hook(frontend,frontend,frontend,native_data,nullptr,nullptr,&native_list,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr);assert(chest.flags==8);c.storage=chest;active=&c;int before_calls=callback_calls;title_hook(&selected,frontend,&label,&label,&icon,&title_size);assert(callback_calls==before_calls);active=nullptr;
 native_tag=tag;active=&c;drawing=&sections[0];c.ui=frontend;assert(compact_row("icons",3));assert(symbol_button("deposit","->","Deposit all into this storage",0));assert(!symbol_button("bad","toolong","Description",0));end_row();active=nullptr;drawing=nullptr;tip_screen=screen;tip_text=tooltip;tip_position=position;tip_background=background;tooltip_cursor=cursor;screen_columns=40;screen_rows=20;tip_end=screen_end;assert(hover_tip=="Deposit all into this storage");screen_end_hook(frontend);assert(screen_calls==3&&tip_calls==1&&hover_tip.empty()&&tooltip_copy=="Deposit all into this storage");screen_end_hook(frontend);assert(screen_calls==4&&tip_calls==1);
 // Actual native popup coordinates use bottom-origin square cells, including
 // ultrawide viewports. The inventory's 42-cell content width is not the window.
 screen_rows=32;Vec2S32 mouse{},viewport{};assert(cursor_grid({1700,290},{0,0,2560,1440},&mouse,&viewport));assert(mouse.x==37&&mouse.y==25&&viewport.x==56&&viewport.y==32);assert(cursor_grid({0,0},{0,0,2560,1440},&mouse,&viewport)&&mouse.y==31);assert(cursor_grid({2559,1439},{0,0,2560,1440},&mouse,&viewport)&&mouse.y==0);assert(!cursor_grid({-1,0},{0,0,2560,1440},&mouse,&viewport));assert(!cursor_grid({0,1440},{0,0,2560,1440},&mouse,&viewport));assert(cursor_grid({3000,500},{0,0,3440,1440},&mouse,&viewport)&&viewport.x==76);
 // Startup resolver regression: identical text/push bodies must be resolved
 // through actual native dependency cells, never a supposedly unique scan.
 auto chain=(unsigned char*)VirtualAlloc(nullptr,8192,MEM_RESERVE|MEM_COMMIT,PAGE_EXECUTE_READWRITE);assert(chain);auto align_fn=(uintptr_t)(chain+4096),color_fn=(uintptr_t)(chain+5120),text_fn=(uintptr_t)(chain+6144);memcpy((void*)align_fn,ST_TIP_TEXT_ALIGN,sizeof(ST_TIP_TEXT_ALIGN));memcpy((void*)color_fn,ST_TIP_TEXT_COLOR,sizeof(ST_TIP_TEXT_COLOR));memcpy((void*)text_fn,ST_TIP_TEXT,sizeof(ST_TIP_TEXT));put(chain,0xce0,(uintptr_t)&align_fn);put((unsigned char*)align_fn,0x50,(uintptr_t)&color_fn);put((unsigned char*)color_fn,0xf0,(uintptr_t)&text_fn);uintptr_t resolved{};assert(resolve_tip_text((uintptr_t)chain,resolved)&&resolved==text_fn);text_fn=0;assert(!resolve_tip_text((uintptr_t)chain,resolved));VirtualFree(chain,0,MEM_RELEASE);
 std::cout<<"PASS: independent vector byte layout, native crate dispatch/filtering, reserved column height without source mutation, copied collections, transfer IDs and lifecycle\n";
}
