// Generated by tools/sdk_codegen.py. Do not edit; regenerate after every game update.
#pragma once
#include <cstdint>
#include "anymaker_sdk_runtime.hpp"

namespace anymaker::sym {

inline constexpr const char* steam_build_id = "25826614";
inline constexpr uint32_t game_exe_pe_timestamp = 1791540771u;
inline constexpr uint64_t game_gcl_size = 82479913ull;
inline constexpr const char* game_exe_sha256 = "2bfa5396ba49cb902941afe65294403c0222e9266e35ce3e7131cb8185d336f7";
inline constexpr const char* game_gcl_sha256 = "da170da347d494cf78b8ca43592e1981c5950528d27d0564b81ce8144f30622d";

// ---- functions (gcl, JIT-loaded). Resolve with anymaker::resolve(desc) / anymaker::cell_of(desc).
// FN:() server.tick (server)  [direct, via_caller]
inline constexpr func_desc server_tick{"() server.tick (server)", "53 55 56 57 41 54 41 55 41 56 48 81 ec 50 03 00 00 48 89 8c 24 50 02 00 00 48 8d 01 48 8b 15 d5", {"48 81 ec 78 2c 00 00 48 8b 05 32 04 00 00 48 83 78 08 00 0f 95 c0 3c 00 0f 84 fd 03 00 00 48 8d", {1192u}, 1}, "", 0u, -1};
inline constexpr int server_tick_vslot = -1;  // zero-based slot in server's method table, -1 if not virtual
// FN:() client.tick (client, const f64, const bool, frontend_ui, settings)  [direct, via_caller]
inline constexpr func_desc client_tick{"() client.tick (client, const f64, const bool, frontend_ui, settings)", "53 55 56 57 48 81 ec a8 01 00 00 4c 8b 94 24 f0 01 00 00 48 89 8c 24 d0 00 00 00 48 89 94 24 d8", {"53 55 48 81 ec 98 00 00 00 48 8d 4c 24 58 48 8b 05 cb 05 00 00 ff 10 48 8b 05 ca 05 00 00 f2 0f", {1704u}, 1}, "", 0u, -1};
inline constexpr int client_tick_vslot = -1;  // zero-based slot in client's method table, -1 if not virtual
// FN:() server_scene.create (server_scene, const string, const e_gamemode)  [direct, via_typeinfo]
inline constexpr func_desc server_scene_create{"() server_scene.create (server_scene, const string, const e_gamemode)", "53 55 56 48 81 ec 90 06 00 00 48 89 8c 24 c8 04 00 00 48 89 94 24 d0 04 00 00 4c 89 84 24 d8 04", {"", {}, 0}, "53 55 48 83 ec 38 48 89 4c 24 20 48 8d 01 48 8b 15 db 06 00 00 48 89 4c 24 30 48 89 c1 ff 12 48", 1784u, 4};
inline constexpr int server_scene_create_vslot = 4;  // zero-based slot in server_scene's method table, -1 if not virtual
// FN:() server_scene.destroy (server_scene)  [direct, via_typeinfo]
inline constexpr func_desc server_scene_destroy{"() server_scene.destroy (server_scene)", "53 55 48 83 ec 38 48 89 4c 24 20 48 8d 81 38 09 00 00 48 8d 11 48 8b 99 38 09 00 00 48 8b 9b 80", {"", {}, 0}, "53 55 48 83 ec 38 48 89 4c 24 20 48 8d 01 48 8b 15 db 06 00 00 48 89 4c 24 30 48 89 c1 ff 12 48", 1784u, 5};
inline constexpr int server_scene_destroy_vslot = 5;  // zero-based slot in server_scene's method table, -1 if not virtual
// FN:() client_scene.create (client_scene)  [direct, via_typeinfo]
inline constexpr func_desc client_scene_create{"() client_scene.create (client_scene)", "53 55 56 57 41 54 41 55 41 56 41 57 48 81 ec d8 03 00 00 48 89 8c 24 50 03 00 00 48 8d 81 a0 29", {"", {}, 0}, "53 48 83 ec 30 48 89 4c 24 20 48 8d 01 48 8b 15 cc 08 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b", 2280u, 2};
inline constexpr int client_scene_create_vslot = 2;  // zero-based slot in client_scene's method table, -1 if not virtual
// FN:() client_scene.destroy (client_scene, client)  [direct, via_typeinfo]
inline constexpr func_desc client_scene_destroy{"() client_scene.destroy (client_scene, client)", "53 55 48 83 ec 48 48 89 4c 24 20 48 89 54 24 28 48 8b 05 41 04 00 00 f2 0f 10 05 31 04 00 00 f2", {"", {}, 0}, "53 48 83 ec 30 48 89 4c 24 20 48 8d 01 48 8b 15 cc 08 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b", 2280u, 3};
inline constexpr int client_scene_destroy_vslot = 3;  // zero-based slot in client_scene's method table, -1 if not virtual
// FN:() client_scene.update_ui (client_scene, frontend_ui, settings, const f64, client)  [direct, via_typeinfo]
inline constexpr func_desc client_scene_update_ui{"() client_scene.update_ui (client_scene, frontend_ui, settings, const f64, client)", "53 55 48 83 ec 68 48 8b 84 24 a0 00 00 00 48 89 4c 24 30 48 89 54 24 38 4c 89 44 24 40 4c 89 4c 24 48 48 89 44 24 50 48 8d 12", {"", {}, 0}, "53 48 83 ec 30 48 89 4c 24 20 48 8d 01 48 8b 15 cc 08 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b", 2280u, 8};
inline constexpr int client_scene_update_ui_vslot = 8;  // zero-based slot in client_scene's method table, -1 if not virtual
// FN:() state_manager.queue_state (state_manager, frontend_ui, const ref<state_manager.state_base>, const bool, const bool)  [direct, via_caller]
inline constexpr func_desc state_manager_queue_state{"() state_manager.queue_state (state_manager, frontend_ui, const ref<state_manager.state_base>, const bool, const bool)", "53 55 48 83 ec 68 48 8b 9c 24 a0 00 00 00 48 89 4c 24 20 48 89 54 24 28 4c 89 44 24 30 4c 89 4c 24 38 48 89 5c 24 40 48 83", {"53 55 48 81 ec 88 00 00 00 48 89 4c 24 30 48 89 54 24 38 4c 89 44 24 40 48 8b 05 c1 00 00 00 48", {256u}, 1}, "", 0u, -1};
inline constexpr int state_manager_queue_state_vslot = -1;  // zero-based slot in state_manager's method table, -1 if not virtual
// FN:(ptr<server_scene.actor>) server_scene.actor.container.get_actor_by_id (server_scene.actor.container, const s32)  [via_typeinfo]
inline constexpr func_desc actor_container_get_actor_by_id{"(ptr<server_scene.actor>) server_scene.actor.container.get_actor_by_id (server_scene.actor.container, const s32)", "", {"", {}, 0}, "48 83 ec 38 48 89 4c 24 20 48 8d 01 48 8b 15 a5 00 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b 05 9c 00 00 00 48 8b 4c 24 28 48 89 01 8b 05 7e 00 00 00 89 41 78", 192u, 33};
inline constexpr int actor_container_get_actor_by_id_vslot = 33;  // zero-based slot in server_scene.actor.container's method table, -1 if not virtual
// FN:(ptr<server_scene.entity>) server_scene.entity.container.get_entity_by_id (const server_scene.entity.container, const s32)  [via_typeinfo]
inline constexpr func_desc entity_container_get_entity_by_id{"(ptr<server_scene.entity>) server_scene.entity.container.get_entity_by_id (const server_scene.entity.container, const s32)", "", {"", {}, 0}, "48 83 ec 38 48 89 4c 24 20 48 8d 01 48 8b 15 5d 00 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b 05 54 00 00 00 48 8b 4c 24 28 48 89 01 8b 05 36 00 00 00 89 41 78", 120u, 27};
inline constexpr int entity_container_get_entity_by_id_vslot = 27;  // zero-based slot in server_scene.entity.container's method table, -1 if not virtual
// FN:(ptr<server_scene.vehicle>) server_scene.vehicle.container.get_vehicle_by_id (const server_scene.vehicle.container, const s32)  [direct]
inline constexpr func_desc vehicle_container_get_vehicle_by_id{"(ptr<server_scene.vehicle>) server_scene.vehicle.container.get_vehicle_by_id (const server_scene.vehicle.container, const s32)", "48 81 ec 98 00 00 00 48 89 4c 24 48 48 89 54 24 50 4c 89 44 24 58 48 8b 44 24 28 48 89 44 24 60 4c 8d 4c 24 60 48 8d 44 24 68 48 89 84 24 80 00 00 00 48 8d 12 48 8b 05 d4 00 00 00 48 89 4c 24 78 4c 89 c9 48 89 4c 24 40 48 89 54 24 20 4c 89 44 24 38 ff 10 48 8d 44 24 70 48 8b 0d b7 00 00 00 48 89 44 24 30 48 89 8c 24 88 00 00 00 48 8b 84 24 88 00 00 00 48 8b 4c 24 30 48 8b 54 24 20 ff 10 48 8b 44 24 70 48 39 44 24 60 0f 84 63", {"", {}, 0}, "", 0u, -1};
inline constexpr int vehicle_container_get_vehicle_by_id_vslot = 29;  // zero-based slot in server_scene.vehicle.container's method table, -1 if not virtual
// FN:(mat34) server_scene.entity.get_transform (const server_scene.entity)  [via_typeinfo]
inline constexpr func_desc entity_get_transform{"(mat34) server_scene.entity.get_transform (const server_scene.entity)", "", {"", {}, 0}, "48 83 ec 38 48 89 4c 24 20 48 8d 01 48 8b 15 5d 00 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b 05 54 00 00 00 48 8b 4c 24 28 48 89 01 8b 05 36 00 00 00 89 41 40", 120u, 5};
inline constexpr int entity_get_transform_vslot = 5;  // zero-based slot in server_scene.entity's method table, -1 if not virtual
// FN:() server_scene.actor.damage (server_scene.actor, server_scene, const f64, const server_scene.actor_damage_src)  [direct, via_caller, via_typeinfo]
inline constexpr func_desc actor_damage{"() server_scene.actor.damage (server_scene.actor, server_scene, const f64, const server_scene.actor_damage_src)", "53 55 56 48 81 ec 40 01 00 00 48 89 8c 24 b0 00 00 00 48 89 94 24 b8 00 00 00 4c 89 84 24 c0 00 00 00 4c", {"53 55 56 57 48 81 ec a8 00 00 00 48 89 4c 24 58 48 89 54 24 60 4c 89 44 24 68 4c 89 4c 24 70 48 8d 44 24 78 48 8d 19", {840u}, 1}, "53 48 83 ec 30 48 89 4c 24 20 48 8d 01 48 8b 15 a4 01 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b", 448u, 99};
inline constexpr int actor_damage_vslot = 99;  // zero-based slot in server_scene.actor's method table, -1 if not virtual
// FN:(ptr<server_scene.inventory>) server_scene.actor.get_inventory (server_scene.actor)  [via_typeinfo]
inline constexpr func_desc actor_get_inventory{"(ptr<server_scene.inventory>) server_scene.actor.get_inventory (server_scene.actor)", "", {"", {}, 0}, "53 48 83 ec 30 48 89 4c 24 20 48 8d 01 48 8b 15 a4 01 00 00 48 89 4c 24 28 48 89 c1 ff 12 48 8b", 448u, 97};
inline constexpr int actor_get_inventory_vslot = 97;  // zero-based slot in server_scene.actor's method table, -1 if not virtual
// FN:() mm_ui.begin (mm_ui)  [direct, via_caller]
inline constexpr func_desc mm_ui_begin{"() mm_ui.begin (mm_ui)", "53 55 56 48 81 ec 30 02 00 00 48 89 8c 24 b8 01 00 00 8b 05 e0 15 00 00 48 8d 94 24 c0 01 00 00", {"53 55 56 48 81 ec e0 01 00 00 48 8b 05 97 29 00 00 48 8d 08 48 8b 05 95 29 00 00 ff 10 48 8b 2d", {10672u}, 1}, "", 0u, -1};
inline constexpr int mm_ui_begin_vslot = -1;  // zero-based slot in mm_ui's method table, -1 if not virtual
// FN:() mm_ui.end (mm_ui)  [direct, via_caller]
inline constexpr func_desc mm_ui_end{"() mm_ui.end (mm_ui)", "53 55 56 48 81 ec c0 00 00 00 48 89 8c 24 80 00 00 00 48 8d 81 48 02 00 00 48 8b 15 80 03 00 00", {"53 55 56 48 81 ec e0 01 00 00 48 8b 05 97 29 00 00 48 8d 08 48 8b 05 95 29 00 00 ff 10 48 8b 2d", {11192u}, 1}, "", 0u, -1};
inline constexpr int mm_ui_end_vslot = -1;  // zero-based slot in mm_ui's method table, -1 if not virtual
// FN:(bool) mm_ui.button (mm_ui, const string)  [direct, via_caller]
inline constexpr func_desc mm_ui_button{"(bool) mm_ui.button (mm_ui, const string)", "53 55 48 81 ec 48 01 00 00 48 89 8c 24 c8 00 00 00 48 89 94 24 d0 00 00 00 4c 89 84 24 d8 00 00 00 48 8d", {"53 55 48 81 ec b8 02 00 00 48 89 8c 24 60 02 00 00 8b 41 08 3b 05 be 09 00 00 0f 94 c0 3c 00 0f", {2800u}, 1}, "", 0u, -1};
inline constexpr int mm_ui_button_vslot = -1;  // zero-based slot in mm_ui's method table, -1 if not virtual
// FN:() audio_manager.play (audio_manager, const e_audio_effect, const e_audio_group)  [direct, via_caller]
inline constexpr func_desc audio_manager_play{"() audio_manager.play (audio_manager, const e_audio_effect, const e_audio_group)", "53 48 83 ec 70 48 89 4c 24 20 48 89 54 24 28 4c 89 44 24 30 8b 02 48 8d 54 24 40 48 8d 89 88 00", {"48 83 ec 38 48 89 4c 24 20 48 8d 05 58 00 00 00 48 8b 15 61 00 00 00 48 89 4c 24 28 48 89 c1 ff", {144u}, 1}, "", 0u, -1};
inline constexpr int audio_manager_play_vslot = -1;  // zero-based slot in audio_manager's method table, -1 if not virtual
// FN:() server.save_game (server, const string)  [cell_chain, direct]
inline constexpr func_desc server_save_game{"() server.save_game (server, const string)", "53 55 48 83 ec 58 48 89 4c 24 20 48 89 54 24 28 48 8d 44 24 30 48 8d 1d 54 00 00 00 48 8b 2d 55", {"53 55 56 57 48 81 ec 08 05 00 00 48 89 8c 24 68 04 00 00 48 89 94 24 70 04 00 00 4c 89 84 24 78", {6152u, 216u}, 2}, "", 0u, -1};
inline constexpr int server_save_game_vslot = -1;  // zero-based slot in server's method table, -1 if not virtual
// FN:() server_scene.save_data.create_scene_from_data (server_scene.save_data, server_scene)  [direct, via_caller]
inline constexpr func_desc save_create_scene_from_data{"() server_scene.save_data.create_scene_from_data (server_scene.save_data, server_scene)", "53 55 56 48 83 ec 40 48 89 4c 24 20 48 89 54 24 28 48 8d 42 48 48 8d 19 48 8b 6a 48 48 8b ad 80 00 00 00 48 8b 35 8e", {"53 55 56 48 81 ec 90 06 00 00 48 89 8c 24 c8 04 00 00 48 89 94 24 d0 04 00 00 4c 89 84 24 d8 04", {5496u}, 1}, "", 0u, -1};
inline constexpr int save_create_scene_from_data_vslot = -1;  // zero-based slot in server_scene.save_data's method table, -1 if not virtual
// FN:() inventory_definition_container.load (inventory_definition_container, const file.path, const outfit_resources)  [direct, via_caller]
inline constexpr func_desc inventory_definitions_load{"() inventory_definition_container.load (inventory_definition_container, const file.path, const outfit_resources)", "53 55 56 48 81 ec a0 01 00 00 48 89 8c 24 e0 00 00 00 48 89 94 24 e8 00 00 00 4c 89 84 24 f0 00 00 00 48 8d 01", {"53 55 56 57 41 54 41 55 41 56 41 57 48 81 ec d8 03 00 00 48 89 8c 24 50 03 00 00 48 8d 81 a0 29", {5160u}, 1}, "", 0u, -1};
inline constexpr int inventory_definitions_load_vslot = -1;  // zero-based slot in inventory_definition_container's method table, -1 if not virtual
// FN:(ptr<inventory_definition>) inventory_definition_container.get_definition_by_id (inventory_definition_container, const string)  [via_caller]
inline constexpr func_desc inventory_definitions_get_by_id{"(ptr<inventory_definition>) inventory_definition_container.get_definition_by_id (inventory_definition_container, const string)", "", {"53 55 56 57 48 81 ec 58 02 00 00 48 89 8c 24 c0 01 00 00 48 89 94 24 c8 01 00 00 4c 89 84 24 d0", {2696u}, 1}, "", 0u, -1};
inline constexpr int inventory_definitions_get_by_id_vslot = -1;  // zero-based slot in inventory_definition_container's method table, -1 if not virtual
// FN:(bool) client.on_action_digital_begin (client, const s32)  [direct, via_caller]
inline constexpr func_desc client_on_action_digital_begin{"(bool) client.on_action_digital_begin (client, const s32)", "53 55 56 48 81 ec 90 00 00 00 48 89 4c 24 48 48 89 54 24 50 4c 89 44 24 58 8b 05 39 03 00 00 41", {"53 48 83 ec 60 48 89 4c 24 20 48 89 54 24 28 8a 02 3a 05 59 01 00 00 0f 94 c0 3c 00 0f 84 72 00", {432u}, 1}, "", 0u, -1};
inline constexpr int client_on_action_digital_begin_vslot = -1;  // zero-based slot in client's method table, -1 if not virtual
// FN:() client.update_ui_menu_bar (client, frontend_ui)  [direct, via_caller]
inline constexpr func_desc client_update_ui_menu_bar{"() client.update_ui_menu_bar (client, frontend_ui)", "53 48 83 ec 40 48 89 4c 24 20 48 89 54 24 28 8b 41 08 3b 05 60 00 00 00 0f 94 c0 3c 00 0f 84 49", {"53 48 83 ec 50 48 8b 1d 64 08 00 00 48 8d 4c 24 38 48 8d 15 58 07 00 00 48 8b 05 59 08 00 00 ff", {2328u}, 1}, "", 0u, -1};
inline constexpr int client_update_ui_menu_bar_vslot = -1;  // zero-based slot in client's method table, -1 if not virtual
// FN:() ctor (inventory_definition_file)  [via_caller]
inline constexpr func_desc inventory_definition_file_ctor{"() ctor (inventory_definition_file)", "", {"53 55 56 48 81 ec a0 01 00 00 48 89 8c 24 e0 00 00 00 48 89 94 24 e8 00 00 00 4c 89 84 24 f0 00 00 00 48 8d 01", {1256u}, 1}, "", 0u, -1};
inline constexpr int inventory_definition_file_ctor_vslot = -1;  // zero-based slot in None's method table, -1 if not virtual
// FN:() dtor (inventory_definition_file)  [via_caller]
inline constexpr func_desc inventory_definition_file_dtor{"() dtor (inventory_definition_file)", "", {"53 55 56 48 81 ec a0 01 00 00 48 89 8c 24 e0 00 00 00 48 89 94 24 e8 00 00 00 4c 89 84 24 f0 00 00 00 48 8d 01", {1416u}, 1}, "", 0u, -1};
inline constexpr int inventory_definition_file_dtor_vslot = -1;  // zero-based slot in None's method table, -1 if not virtual
// FN:(bool) inventory_definition_file.load (inventory_definition_file, const file.path)  [via_caller]
inline constexpr func_desc inventory_definition_file_load{"(bool) inventory_definition_file.load (inventory_definition_file, const file.path)", "", {"53 55 56 48 81 ec a0 01 00 00 48 89 8c 24 e0 00 00 00 48 89 94 24 e8 00 00 00 4c 89 84 24 f0 00 00 00 48 8d 01", {1264u}, 1}, "", 0u, -1};
inline constexpr int inventory_definition_file_load_vslot = -1;  // zero-based slot in inventory_definition_file's method table, -1 if not virtual
// FN:() inventory_definition_container._add_definitions (inventory_definition_container, const inventory_definition_file, const outfit_resources)  [direct, via_caller]
inline constexpr func_desc inventory_definitions_add_definitions{"() inventory_definition_container._add_definitions (inventory_definition_container, const inventory_definition_file, const outfit_resources)", "53 55 56 48 81 ec 00 02 00 00 48 89 8c 24 28 01 00 00 48 89 94 24 30 01 00 00 4c 89 84 24 38 01", {"53 55 56 48 81 ec a0 01 00 00 48 89 8c 24 e0 00 00 00 48 89 94 24 e8 00 00 00 4c 89 84 24 f0 00 00 00 48 8d 01", {1280u}, 1}, "", 0u, -1};
inline constexpr int inventory_definitions_add_definitions_vslot = -1;  // zero-based slot in inventory_definition_container's method table, -1 if not virtual

// ---- natives (game.exe RVAs). Evidence: metadata (static scan) and/or runtime (call cells).
inline constexpr uint32_t string_ctor_cstr_rva = 0x4f050;  // N:() $string_ctor_cstr (string, const uptr) [metadata]
inline constexpr uint32_t string_dtor_rva = 0x4f1d0;  // N:() $string_dtor (string) [metadata]
inline constexpr uint32_t string_length_rva = 0x25e10;  // N:(s32) string.length (const string) [metadata]
inline constexpr uint32_t file_write_string_rva = 0x3f0b0;  // N:(bool) file.write_string (const file.path, const string) [metadata]
inline constexpr uint32_t file_read_string_rva = 0x3f080;  // N:(bool) file.read_string (const file.path, string) [metadata]
inline constexpr uint32_t file_get_is_exists_rva = 0x3f140;  // N:(bool) file.get_is_exists (const file.path) [metadata]

// ---- globals: address = slot at anchor+slot_offset (anchors.json; runtime-validated layout)
inline constexpr global_desc g_server{"g_server", "48 83 ec 48 48 89 4c 24 20 48 89 54 24 28 48 8d 8a d0 43 00 00 48 8b 05 bc 00 00 00 48 89 54 24", 224u};  // G:g_server
inline constexpr global_desc g_client{"g_client", "48 83 ec 38 48 89 4c 24 20 48 89 54 24 28 48 8b 05 4b 00 00 00 48 83 78 08 00 0f 95 c0 3c 00 0f", 96u};  // G:g_client
inline constexpr global_desc g_settings{"g_settings", "48 83 ec 08 48 89 0c 24 48 8b 05 11 00 00 00 8b 40 04 89 01 e9 00 00 00 00 48 83 c4 08 c3 00 00", 32u};  // G:g_settings
inline constexpr global_desc g_state_manager{"g_state_manager", "53 55 48 81 ec 88 00 00 00 48 89 4c 24 30 48 89 54 24 38 4c 89 44 24 40 48 8b 05 c1 00 00 00 48", 248u};  // G:g_state_manager
inline constexpr global_desc g_ui{"g_ui", "53 48 83 ec 40 48 89 4c 24 20 48 8b 05 4f 00 00 00 48 8d 00 48 8d 11 48 8b 1d 4a 00 00 00 48 89", 96u};  // G:g_ui
inline constexpr global_desc g_frontend_ui{"g_frontend_ui", "53 48 83 ec 40 48 89 4c 24 20 48 8b 05 4f 00 00 00 48 8d 00 48 8d 11 48 8b 1d 4a 00 00 00 48 89", 112u};  // G:g_frontend_ui
inline constexpr global_desc g_audio_manager{"g_audio_manager", "48 83 ec 38 48 89 4c 24 20 48 8d 05 58 00 00 00 48 8b 15 61 00 00 00 48 89 4c 24 28 48 89 c1 ff", 136u};  // G:g_audio_manager
inline constexpr global_desc g_localization{"g_localization", "48 83 ec 38 48 89 4c 24 20 48 89 54 24 28 48 8b 05 2b 00 00 00 48 8d 09 48 8d 10 4c 8d 05 16 00 00 00 48 8b 05 1f 00 00 00 ff 10 e9 00 00 00 00 48 83 c4 38 c3 00 00 00 f3", 64u};  // G:g_localization
inline constexpr global_desc g_renderer{"g_renderer", "48 83 ec 18 48 89 0c 24 48 89 54 24 08 48 8b 05 14 00 00 00 48 8b 80 08 05 00 00 48 89 01 e9 00", 40u};  // G:g_renderer
inline constexpr global_desc g_input{"g_input", "48 83 ec 38 48 89 4c 24 20 48 89 54 24 28 8a 02 88 81 53 04 00 00 48 8b 05 13 00 00 00 48 8d 08", 48u};  // G:g_input

// ---- field offsets (metadata)
inline constexpr uint32_t off_server__m_scene = 0x98;  // F:server::m_scene : ref<server_scene>
inline constexpr uint32_t off_server__m_network_state = 0x8;  // F:server::m_network_state : e_server_network_state
inline constexpr uint32_t off_client__m_scene = 0xf50;  // F:client::m_scene : client_scene
inline constexpr uint32_t off_server_scene__m_peers = 0xa8;  // F:server_scene::m_peers : server_scene.peer.container
inline constexpr uint32_t off_server_scene__m_actors = 0x250;  // F:server_scene::m_actors : server_scene.actor.container
inline constexpr uint32_t off_server_scene__m_vehicles = 0x1b0;  // F:server_scene::m_vehicles : server_scene.vehicle.container
inline constexpr uint32_t off_server_scene__m_entities = 0x430;  // F:server_scene::m_entities : server_scene.entity.container
inline constexpr uint32_t off_server_scene__m_physics = 0xa60;  // F:server_scene::m_physics : physics.scene
inline constexpr uint32_t off_server_scene__m_inventory_definitions = 0xf80;  // F:server_scene::m_inventory_definitions : inventory_definition_container
inline constexpr uint32_t off_server_scene__m_version = 0x40;  // F:server_scene::m_version : s32
inline constexpr uint32_t off_server_scene_actor__m_id = 0x40;  // F:server_scene.actor::m_id : s32
inline constexpr uint32_t off_server_scene_actor__m_transform = 0x150;  // F:server_scene.actor::m_transform : mat34
inline constexpr uint32_t off_server_scene_actor__m_peer_authority = 0x1b0;  // F:server_scene.actor::m_peer_authority : ptr<server_scene.peer>
inline constexpr uint32_t off_server_scene_entity__m_id = 0x40;  // F:server_scene.entity::m_id : s32
inline constexpr uint32_t off_server_scene_entity__m_transform = 0x48;  // F:server_scene.entity::m_transform : mat34
inline constexpr uint32_t off_server_scene_vehicle__m_id = 0x40;  // F:server_scene.vehicle::m_id : s32
inline constexpr uint32_t off_server_scene_peer__m_unique_identifier = 0x18;  // F:server_scene.peer::m_unique_identifier : string
inline constexpr uint32_t off_server_scene_peer__m_authority_actor = 0x19b8;  // F:server_scene.peer::m_authority_actor : ptr<server_scene.actor>
inline constexpr uint32_t off_server_scene_actor_damage_src__m_actor_id_src = 0x0;  // F:server_scene.actor_damage_src::m_actor_id_src : s32
inline constexpr uint32_t off_server_scene_actor_damage_src__m_type = 0x4;  // F:server_scene.actor_damage_src::m_type : e_actor_damage_type
inline constexpr uint32_t off_server_scene_actor_damage_src__m_position = 0x8;  // F:server_scene.actor_damage_src::m_position : vec3
inline constexpr uint32_t off_server_scene_actor_damage_src__m_normal = 0x20;  // F:server_scene.actor_damage_src::m_normal : vec3
inline constexpr uint32_t off_server_scene_actor_damage_src__m_hit_flesh_effect = 0x38;  // F:server_scene.actor_damage_src::m_hit_flesh_effect : s32

// ---- sizes (metadata)
inline constexpr uint32_t size_server_scene_actor_damage_src = 0x40;  // T:server_scene.actor_damage_src
inline constexpr uint32_t size_mat34 = 0x60;  // T:mat34
inline constexpr uint32_t size_vec3 = 0x18;  // T:vec3
inline constexpr uint32_t size_inventory_definition_file = 0x28;  // T:inventory_definition_file
inline constexpr uint32_t size_file_path = 0x18;  // T:file.path
inline constexpr uint32_t size_outfit_resources = 0x1c8;  // T:outfit_resources

// ---- enums (value = position in the recorded name table: static inference, see docs)
namespace file_e_store {  // T:file.e_store
inline constexpr int32_t embedded = 0;
inline constexpr int32_t system = 1;
inline constexpr int32_t rom = 2;
inline constexpr int32_t user = 3;
}
namespace e_actor_damage_type {  // T:e_actor_damage_type
inline constexpr int32_t weapon_melee = 0;
inline constexpr int32_t weapon_gun = 1;
inline constexpr int32_t impact = 2;
inline constexpr int32_t weapon_grenade = 3;
inline constexpr int32_t environment_explosion = 4;
inline constexpr int32_t injury = 5;
inline constexpr int32_t acid = 6;
}
namespace e_audio_group {  // T:e_audio_group
inline constexpr int32_t ui = 0;
inline constexpr int32_t music = 1;
inline constexpr int32_t environment = 2;
inline constexpr int32_t environment_3d = 3;
inline constexpr int32_t vehicle = 4;
inline constexpr int32_t actor = 5;
inline constexpr int32_t actor_stun = 6;
inline constexpr int32_t voice = 7;
}
namespace state_manager_e_state {  // T:state_manager.e_state
inline constexpr int32_t none = 0;
inline constexpr int32_t logo = 1;
inline constexpr int32_t warning = 2;
inline constexpr int32_t main_menu = 3;
inline constexpr int32_t end_main_menu_begin_host_new_game = 4;
inline constexpr int32_t end_main_menu_begin_host_save_game = 5;
inline constexpr int32_t unload_game_begin_host_save_game = 6;
inline constexpr int32_t end_main_menu_begin_join_local_game = 7;
inline constexpr int32_t unload_game_begin_join_local_game = 8;
inline constexpr int32_t end_main_menu_begin_join_invite_code_game = 9;
inline constexpr int32_t end_main_menu_begin_join_rich_presence_game = 10;
inline constexpr int32_t unload_game_begin_join_rich_presence_game = 11;
inline constexpr int32_t connect_to_game = 12;
inline constexpr int32_t load_game = 13;
inline constexpr int32_t load_game_teleport = 14;
inline constexpr int32_t game = 15;
inline constexpr int32_t unload_game_to_main_menu = 16;
inline constexpr int32_t game_banned = 17;
}
namespace e_gamemode {  // T:e_gamemode
inline constexpr int32_t survival = 0;
inline constexpr int32_t creative = 1;
inline constexpr int32_t sandbox = 2;
}

}  // namespace anymaker::sym
