#pragma once
#include <d3d12.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <algorithm>
#include <utility>
#include "volumetric_frame.h"
#include "volumetric_bytecode.h"
namespace volumetric {
using Microsoft::WRL::ComPtr;
inline D3D12_RESOURCE_BARRIER barrier(ID3D12Resource* resource,D3D12_RESOURCE_STATES from,D3D12_RESOURCE_STATES to){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={resource,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,from,to};return b;}
class Gpu {
 ComPtr<ID3D12Device> device;ComPtr<ID3D12CommandQueue> queue;
 ComPtr<ID3D12RootSignature> root;ComPtr<ID3D12PipelineState> integrate,composite;
 ComPtr<ID3D12Resource> source,volume,depth_input,shadow_input;
 ComPtr<ID3D12DescriptorHeap> srv,rtv;UINT width{},height{},srv_stride{},rtv_stride{};DXGI_FORMAT format{};bool read{};HRESULT last_error{};
 bool checked(HRESULT h){last_error=h;return SUCCEEDED(h);}
 D3D12_CPU_DESCRIPTOR_HANDLE cpu(UINT i){auto h=srv->GetCPUDescriptorHandleForHeapStart();h.ptr+=SIZE_T(i)*srv_stride;return h;}
 D3D12_CPU_DESCRIPTOR_HANDLE output(UINT i){auto h=rtv->GetCPUDescriptorHandleForHeapStart();h.ptr+=SIZE_T(i)*rtv_stride;return h;}
 bool idle(){ComPtr<ID3D12Fence> f;if(!device||!queue||FAILED(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)))||FAILED(queue->Signal(f.Get(),1)))return false;HANDLE e=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!e)return false;bool ok=SUCCEEDED(f->SetEventOnCompletion(1,e))&&WaitForSingleObject(e,3000)==WAIT_OBJECT_0;CloseHandle(e);return ok;}
 bool texture(ComPtr<ID3D12Resource>& out,UINT w,UINT h,DXGI_FORMAT f,bool render){D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC td{};td.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;td.Width=w;td.Height=h;td.DepthOrArraySize=1;td.MipLevels=1;td.Format=f;td.SampleDesc.Count=1;td.Flags=render?D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET:D3D12_RESOURCE_FLAG_NONE;return checked(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_COMMON,nullptr,IID_PPV_ARGS(&out)));}
 void view(UINT i,ID3D12Resource* resource,DXGI_FORMAT f){D3D12_SHADER_RESOURCE_VIEW_DESC sd{};sd.Format=f;sd.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;sd.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sd.Texture2D.MipLevels=1;device->CreateShaderResourceView(resource,&sd,cpu(i));}
 template<size_t N> bool pipeline(ComPtr<ID3D12PipelineState>& out,const unsigned char(&ps)[N],DXGI_FORMAT f){D3D12_GRAPHICS_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.VS={volumetric_bytecode::Vertex,sizeof(volumetric_bytecode::Vertex)};pd.PS={ps,N};pd.BlendState.RenderTarget[0].RenderTargetWriteMask=15;pd.SampleMask=UINT_MAX;pd.RasterizerState.FillMode=D3D12_FILL_MODE_SOLID;pd.RasterizerState.CullMode=D3D12_CULL_MODE_NONE;pd.RasterizerState.DepthClipEnable=TRUE;pd.PrimitiveTopologyType=D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;pd.NumRenderTargets=1;pd.RTVFormats[0]=f;pd.SampleDesc.Count=1;return checked(device->CreateGraphicsPipelineState(&pd,IID_PPV_ARGS(&out)));}
 bool initialize(ID3D12Device* d,ID3D12CommandQueue* q,const D3D12_RESOURCE_DESC& desc){device=d;queue=q;width=UINT(desc.Width);height=desc.Height;format=desc.Format;D3D12_DESCRIPTOR_RANGE range{};range.RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_SRV;range.NumDescriptors=4;
  D3D12_ROOT_PARAMETER params[2]{};params[0].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;params[0].Constants={0,0,56};params[0].ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;params[1].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;params[1].DescriptorTable={1,&range};params[1].ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;
  D3D12_STATIC_SAMPLER_DESC samplers[2]{};for(UINT i=0;i<2;++i){auto& s=samplers[i];s.Filter=i?D3D12_FILTER_MIN_MAG_MIP_POINT:D3D12_FILTER_MIN_MAG_MIP_LINEAR;s.AddressU=s.AddressV=s.AddressW=D3D12_TEXTURE_ADDRESS_MODE_CLAMP;s.MaxLOD=D3D12_FLOAT32_MAX;s.ShaderRegister=i;s.ShaderVisibility=D3D12_SHADER_VISIBILITY_PIXEL;}
  D3D12_ROOT_SIGNATURE_DESC rd{2,params,2,samplers,D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT};ComPtr<ID3DBlob> code,error;if(!checked(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&code,&error))||!checked(device->CreateRootSignature(0,code->GetBufferPointer(),code->GetBufferSize(),IID_PPV_ARGS(&root))))return false;
  if(!pipeline(integrate,volumetric_bytecode::Integrate,DXGI_FORMAT_R16G16B16A16_FLOAT)||!pipeline(composite,volumetric_bytecode::Composite,format))return false;
  D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=4;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;if(!checked(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&srv))))return false;hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=2;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_NONE;if(!checked(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&rtv))))return false;srv_stride=device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);rtv_stride=device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);
  if(!texture(source,width,height,format,false)||!texture(volume,(width+1)/2,(height+1)/2,DXGI_FORMAT_R16G16B16A16_FLOAT,true))return false;view(0,source.Get(),format);view(3,volume.Get(),DXGI_FORMAT_R16G16B16A16_FLOAT);device->CreateRenderTargetView(volume.Get(),nullptr,output(0));return true;
 }
public:
 HRESULT error()const{return last_error;}
 bool ensure(ID3D12Device* d,ID3D12CommandQueue* q,const D3D12_RESOURCE_DESC& desc){if(!d||!q||desc.Dimension!=D3D12_RESOURCE_DIMENSION_TEXTURE2D||desc.SampleDesc.Count!=1||desc.DepthOrArraySize!=1||!desc.Width||!desc.Height||desc.Width>8192||desc.Height>8192||(desc.Format!=DXGI_FORMAT_R16G16B16A16_FLOAT&&desc.Format!=DXGI_FORMAT_R8G8B8A8_UNORM&&desc.Format!=DXGI_FORMAT_B8G8R8A8_UNORM))return false;if(source&&device.Get()==d&&queue.Get()==q&&width==desc.Width&&height==desc.Height&&format==desc.Format)return true;if(device&&!idle())return false;Gpu next;if(!next.initialize(d,q,desc)){last_error=next.error();return false;}*this=std::move(next);return true;}
 // Borrowed native targets are sampled only for this pass. Their original
 // states and all caller bindings must be restored before the native code resumes.
 bool record(ID3D12GraphicsCommandList* list,ID3D12Resource* target,ID3D12Resource* depth,D3D12_RESOURCE_STATES depth_state,ID3D12Resource* shadow,D3D12_RESOURCE_STATES shadow_state,const Frame& f){
  if(!source||!list||!target||!depth||!shadow||!valid(f)||target==depth||target==shadow)return false;auto dd=depth->GetDesc(),sd=shadow->GetDesc();auto supported=[](const D3D12_RESOURCE_DESC& d,bool shadow){return d.Dimension==D3D12_RESOURCE_DIMENSION_TEXTURE2D&&d.SampleDesc.Count==1&&d.DepthOrArraySize==1&&!(d.Flags&D3D12_RESOURCE_FLAG_DENY_SHADER_RESOURCE)&&(d.Format==DXGI_FORMAT_R32_TYPELESS||d.Format==DXGI_FORMAT_R32_FLOAT||(shadow&&(d.Format==DXGI_FORMAT_R16_TYPELESS||d.Format==DXGI_FORMAT_R16_UNORM)));};if(!supported(dd,false)||!supported(sd,true)||dd.Width!=width||dd.Height!=height)return false;
  if(depth_input.Get()!=depth||shadow_input.Get()!=shadow){if(depth_input&&!idle())return false;depth_input=depth;shadow_input=shadow;view(1,depth,DXGI_FORMAT_R32_FLOAT);view(2,shadow,sd.Format==DXGI_FORMAT_R16_TYPELESS||sd.Format==DXGI_FORMAT_R16_UNORM?DXGI_FORMAT_R16_UNORM:DXGI_FORMAT_R32_FLOAT);}
  D3D12_RESOURCE_BARRIER start[]={barrier(target,D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_COPY_SOURCE),barrier(source.Get(),read?D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE:D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_DEST)};list->ResourceBarrier(2,start);list->CopyResource(source.Get(),target);D3D12_RESOURCE_BARRIER copied[]={barrier(target,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_RENDER_TARGET),barrier(source.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE),barrier(volume.Get(),read?D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE:D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_RENDER_TARGET)};list->ResourceBarrier(3,copied);
  if(depth_state!=D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE){auto b=barrier(depth,depth_state,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);list->ResourceBarrier(1,&b);}if(shadow!=depth&&shadow_state!=D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE){auto b=barrier(shadow,shadow_state,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);list->ResourceBarrier(1,&b);}
  list->SetGraphicsRootSignature(root.Get());ID3D12DescriptorHeap* heap=srv.Get();list->SetDescriptorHeaps(1,&heap);list->SetGraphicsRoot32BitConstants(0,56,&f,0);list->SetGraphicsRootDescriptorTable(1,srv->GetGPUDescriptorHandleForHeapStart());list->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
  D3D12_VIEWPORT viewport{0,0,float((width+1)/2),float((height+1)/2),0,1};D3D12_RECT scissor{0,0,LONG((width+1)/2),LONG((height+1)/2)};list->RSSetViewports(1,&viewport);list->RSSetScissorRects(1,&scissor);auto handle=output(0);list->OMSetRenderTargets(1,&handle,FALSE,nullptr);list->SetPipelineState(integrate.Get());list->DrawInstanced(3,1,0,0);
  auto b=barrier(volume.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);list->ResourceBarrier(1,&b);viewport.Width=float(width);viewport.Height=float(height);scissor.right=LONG(width);scissor.bottom=LONG(height);list->RSSetViewports(1,&viewport);list->RSSetScissorRects(1,&scissor);device->CreateRenderTargetView(target,nullptr,output(1));handle=output(1);list->OMSetRenderTargets(1,&handle,FALSE,nullptr);list->SetPipelineState(composite.Get());list->DrawInstanced(3,1,0,0);
  if(depth_state!=D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE){b=barrier(depth,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,depth_state);list->ResourceBarrier(1,&b);}if(shadow!=depth&&shadow_state!=D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE){b=barrier(shadow,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,shadow_state);list->ResourceBarrier(1,&b);}read=true;return true;
 }
};
}
